# -*- coding: utf-8 -*-
"""arkanoide1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LAaEHYw3ReokE8EwhUqA2AiJr0CoITHb
"""

# -*- coding: utf-8 -*-
from IPython.display import display, HTML

html = """
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<style>
body {
  background: #2a2a4a;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 10px;
  font-family: monospace;
}
.window {
  background: #c0c0c0;
  border: 2px solid #fff;
  border-right-color: #444;
  border-bottom-color: #444;
  box-shadow: 2px 2px 0 #000;
}
.titlebar {
  background: linear-gradient(to right, #000080, #1084d0);
  color: white;
  padding: 3px 6px;
  font-size: 12px;
  font-family: Tahoma, sans-serif;
  display: flex;
  align-items: center;
  gap: 4px;
  user-select: none;
}
.titlebar-btns { margin-left: auto; display: flex; gap: 2px; }
.titlebar-btns button {
  width: 16px; height: 14px;
  background: #c0c0c0;
  border: 1px solid #fff;
  border-right-color: #444;
  border-bottom-color: #444;
  font-size: 10px; cursor: pointer; font-family: monospace; line-height: 1;
}
.game-container {
  display: flex; background: #c0c0c0; padding: 4px; gap: 4px;
}
.game-area { border: 2px inset #888; background: #000080; position: relative; }
canvas#gc { display: block; }
.side-panel {
  width: 160px; background: #c0c0c0;
  border: 2px inset #888; padding: 6px;
  display: flex; flex-direction: column; gap: 5px;
}
.panel-title {
  background: linear-gradient(to right, #000080, #1084d0);
  color: #fff; font-size: 18px; text-align: center;
  padding: 2px 0; font-family: monospace; letter-spacing: 1px;
}
.panel-box {
  background: #fff; border: 2px inset #888; padding: 4px;
}
.panel-box label {
  font-size: 10px; color: #000080;
  font-family: Tahoma, sans-serif; display: block;
}
.panel-value {
  font-family: monospace; font-size: 22px;
  color: #cc0000; text-align: center; display: block;
}
.bingo-grid {
  display: grid; grid-template-columns: repeat(5, 1fr); gap: 2px; margin-top: 4px;
}
.bingo-cell {
  width: 23px; height: 23px; background: #e0e0e0;
  border: 1px solid #888; border-right-color: #fff; border-bottom-color: #fff;
  display: flex; align-items: center; justify-content: center;
  font-size: 10px; font-family: Tahoma, sans-serif;
}
.bingo-cell.marked { background: #ffaa00; border-color: #cc8800; font-weight: bold; }
.bingo-cell.bonus  { background: #ff4444; color: white; border-color: #cc0000; }
.bingo-header {
  font-size: 11px; font-family: Tahoma, sans-serif; color: #000080;
  font-weight: bold; text-align: center;
  border-bottom: 1px solid #888; padding-bottom: 2px; margin-bottom: 2px;
}
.lives-row {
  display: flex; gap: 3px; align-items: center; justify-content: center; padding: 3px;
}
.heart { font-size: 16px; }
.pu-list { display: flex; flex-direction: column; gap: 2px; }
.pu-item { display: flex; align-items: center; gap: 4px; font-size: 10px; font-family: Tahoma, sans-serif; }
.pu-dot { width: 10px; height: 10px; border-radius: 50%; display: inline-block; }
.active-pu {
  background: #ffff88; border: 1px solid #cccc00; border-radius: 3px;
  padding: 1px 3px; font-size: 9px; font-family: Tahoma, sans-serif; font-weight: bold;
}
.info-bar {
  background: #c0c0c0; border-top: 1px solid #888;
  padding: 2px 6px; font-size: 10px; font-family: Tahoma, sans-serif; color: #444;
}
</style>
</head>
<body>
<div class="window">
  <div class="titlebar">
    <span>&#127918;</span>
    <span>BT UE4. Arkanoid by midea</span>
    <div class="titlebar-btns">
      <button>_</button><button>&#9633;</button><button>&#10005;</button>
    </div>
  </div>
  <div class="game-container">
    <div class="game-area">
      <canvas id="gc" width="480" height="520"></canvas>
    </div>
    <div class="side-panel">
      <div class="panel-title">Arkanoid.-</div>
      <div class="panel-box">
        <label>Puntos:</label>
        <span class="panel-value" id="scoreDisp">0000000</span>
      </div>
      <div class="panel-box">
        <label>Nivel:</label>
        <span class="panel-value" id="levelDisp">1</span>
      </div>
      <div class="panel-box">
        <label>Vidas:</label>
        <div class="lives-row" id="livesDisp"></div>
      </div>
      <div class="panel-box">
        <div class="bingo-header">TABLA BONUS</div>
        <div class="bingo-grid" id="bingoGrid"></div>
      </div>
      <div class="panel-box">
        <label>Power-ups:</label>
        <div class="pu-list">
          <div class="pu-item"><span class="pu-dot" style="background:#32dc50"></span> +W amplia</div>
          <div class="pu-item"><span class="pu-dot" style="background:#00dcff"></span> SL lento</div>
          <div class="pu-item"><span class="pu-dot" style="background:#ff64b4"></span> +1 vida</div>
          <div class="pu-item"><span class="pu-dot" style="background:#ff3232"></span> -W encoge</div>
        </div>
        <div id="activePU" style="margin-top:4px;min-height:14px;"></div>
      </div>
    </div>
  </div>
  <div class="info-bar">
    Click juego primero &middot; Flechas/AD mover &middot; ESPACIO lanzar &middot; P pausa &middot; R reiniciar &middot; ESC menu
  </div>
</div>
<script>
(function(){
var cv=document.getElementById('gc');
var cx=cv.getContext('2d');
var W=480,H=520;

// Bingo
var bingoNums=[];
for(var i=1;i<=50;i++) bingoNums.push(i);
for(var i=bingoNums.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=bingoNums[i];bingoNums[i]=bingoNums[j];bingoNums[j]=t;}
var bingoMarked=new Set();
var bonusCells=new Set([4,12,24,33,44]);

function renderBingo(){
  var grid=document.getElementById('bingoGrid');
  grid.innerHTML='';
  bingoNums.forEach(function(n,i){
    var cell=document.createElement('div');
    var cls='bingo-cell';
    if(bingoMarked.has(n)) cls+=' marked';
    else if(bonusCells.has(i)) cls+=' bonus';
    cell.className=cls;
    cell.textContent=n;
    grid.appendChild(cell);
  });
}
renderBingo();

function markBingo(){
  var unmarked=bingoNums.filter(function(n){return !bingoMarked.has(n);});
  if(!unmarked.length) return;
  var pick=unmarked[Math.floor(Math.random()*unmarked.length)];
  bingoMarked.add(pick);
  renderBingo();
}

function updateHUD(){
  document.getElementById('scoreDisp').textContent=String(score).padStart(7,'0');
  document.getElementById('levelDisp').textContent=lv;
  var ld=document.getElementById('livesDisp');
  ld.innerHTML='';
  for(var i=0;i<Math.min(lives,6);i++){
    var h=document.createElement('span');h.className='heart';h.textContent='\u2665';h.style.color='#ff3264';ld.appendChild(h);
  }
  var apuDiv=document.getElementById('activePU');
  if(pad.pw){
    apuDiv.innerHTML='<span class="active-pu" style="color:'+(pad.pw==='expand'?'#005500':'#880000')+'">'+(pad.pw==='expand'?'+W ACTIVO':'-W ACTIVO')+'</span>';
  } else if(ball&&ball.slowed){
    apuDiv.innerHTML='<span class="active-pu" style="color:#005588">SL ACTIVO</span>';
  } else {
    apuDiv.innerHTML='';
  }
}

// Game constants
var BCOLS=10,BW=40,BH=16,BXG=3,BYG=3;
var BX0=Math.floor((W-BCOLS*(BW+BXG)+BXG)/2);
var BY0=30;
var BALL_R=6,PAD_BASE=80,PAD_H=10,PAD_SPD=6,PAD_Y=H-36;

var BCOLORS={
  1:{fill:'#3090ff',shine:'#80c0ff',shadow:'#103080'},
  2:{fill:'#ff8020',shine:'#ffb060',shadow:'#803000'},
  3:{fill:'#ff2040',shine:'#ff7080',shadow:'#800020'},
  4:{fill:'#d020d0',shine:'#f070f0',shadow:'#600060'},
  5:{fill:'#20c050',shine:'#70e090',shadow:'#006020'},
  steel:{fill:'#8898aa',shine:'#bbccdd',shadow:'#445566'}
};

var LVS=[
  [[1,1,1,1,1,1,1,1,1,1],[1,2,2,2,2,2,2,2,2,1],[1,2,3,3,3,3,3,3,2,1],
   [0,1,2,3,2,3,2,2,1,0],[0,0,1,2,3,3,2,1,0,0],[0,0,0,1,2,2,1,0,0,0],[0,0,0,0,1,1,0,0,0,0]],
  [[2,2,2,2,2,2,2,2,2,2],[2,1,1,1,1,1,1,1,1,2],[2,1,9,3,3,3,3,9,1,2],
   [2,1,3,2,2,2,2,3,1,2],[2,1,9,3,3,3,3,9,1,2],[2,1,1,1,1,1,1,1,1,2],[2,2,2,2,2,2,2,2,2,2]],
  [[3,3,3,3,3,3,3,3,3,3],[3,9,2,2,2,2,2,2,9,3],[3,2,4,4,4,4,4,4,2,3],
   [3,2,4,9,3,3,9,4,2,3],[3,2,4,4,4,4,4,4,2,3],[3,9,2,2,2,2,2,2,9,3],[3,3,3,3,3,3,3,3,3,3]]
];

var ST='menu',score=0,lives=3,lv=1,combo=0,maxCombo=0;
var bricks=[],pups=[],pad,ball,msgT=0,tt=0,at=0;
var keys={};

cv.setAttribute('tabindex','0');
cv.addEventListener('click',function(){cv.focus();});

cv.addEventListener('keydown',function(e){
  keys[e.code]=true;
  if(ST==='launching'&&(e.code==='Space'||e.code==='Enter')) ST='playing';
  else if(e.code==='KeyP'){
    if(ST==='playing'||ST==='launching') ST='paused';
    else if(ST==='paused') ST='playing';
  } else if(e.code==='KeyR'){
    if(['playing','launching','paused','gameover','victory'].indexOf(ST)>=0) loadLv();
  } else if(e.code==='Escape'){
    if(ST!=='menu') ST='menu';
  }
  e.preventDefault();
});
cv.addEventListener('keyup',function(e){keys[e.code]=false;});
cv.addEventListener('click',function(e){
  var r=cv.getBoundingClientRect();
  var mx=(e.clientX-r.left)*(W/r.width);
  var my=(e.clientY-r.top)*(H/r.height);
  onClick(mx,my);
});

function onClick(mx,my){
  if(ST==='menu'){
    ['Jugar','Instrucciones','Creditos'].forEach(function(l,i){
      var bx=W/2-100,by=H/2-20+i*54,bw=200,bh=40;
      if(mx>=bx&&mx<=bx+bw&&my>=by&&my<=by+bh){
        if(i===0) newGame(); else if(i===1) ST='instructions'; else ST='credits';
      }
    });
  } else if(ST==='launching') ST='playing';
  else if(ST==='gameover'||ST==='victory'){
    if(mx>=W/2-160&&mx<=W/2-20&&my>=H/2+80&&my<=H/2+120) newGame();
    if(mx>=W/2+20&&mx<=W/2+180&&my>=H/2+80&&my<=H/2+120) ST='menu';
  }
}

function newGame(){score=0;lives=3;lv=1;combo=0;maxCombo=0;bingoMarked.clear();renderBingo();loadLv();}
function loadLv(){
  pups=[];
  pad={x:(W-PAD_BASE)/2,y:PAD_Y,w:PAD_BASE,pw:null,pt:0};
  bricks=[];
  var grid=LVS[Math.min(lv-1,2)];
  grid.forEach(function(row,ri){row.forEach(function(v,ci){
    if(!v) return;
    var type=v===9?'steel':'normal';
    bricks.push({x:BX0+ci*(BW+BXG),y:BY0+ri*(BH+BYG),hp:v===9?99:v,maxHp:v===9?99:v,type:type,alive:true,ft:0});
  });});
  var spd=4+(lv-1)*0.6;
  var ang=(Math.random()*70-35)*Math.PI/180;
  ball={x:pad.x+pad.w/2,y:pad.y-BALL_R-1,vx:spd*Math.sin(ang),vy:-spd*Math.cos(ang),trail:[],slowed:false,st:0};
  combo=0; ST='launching'; updateHUD();
}

function overlap(ax,ay,aw,ah,bx,by,bw,bh){return ax<bx+bw&&ax+aw>bx&&ay<by+bh&&ay+ah>by;}

function updPad(dt){
  if(keys['ArrowLeft']||keys['KeyA']) pad.x-=PAD_SPD;
  if(keys['ArrowRight']||keys['KeyD']) pad.x+=PAD_SPD;
  pad.x=Math.max(0,Math.min(W-pad.w,pad.x));
  if(pad.pw){pad.pt-=dt;if(pad.pt<=0){pad.w=PAD_BASE;pad.pw=null;pad.x=Math.max(0,Math.min(W-pad.w,pad.x));}}
}
function applyPadPU(type){
  if(type==='expand'){pad.w=Math.round(PAD_BASE*1.6);pad.pw='expand';pad.pt=8;}
  if(type==='shrink'){pad.w=Math.round(PAD_BASE*0.6);pad.pw='shrink';pad.pt=6;}
  pad.x=Math.max(0,Math.min(W-pad.w,pad.x));
}
function drawPad(){
  var col=pad.pw==='expand'?'#00e060':pad.pw==='shrink'?'#ff6600':'#00aaff';
  var top=pad.pw==='expand'?'#80ffa0':pad.pw==='shrink'?'#ffaa44':'#80ddff';
  var bot=pad.pw==='expand'?'#006620':pad.pw==='shrink'?'#993300':'#004488';
  cx.fillStyle=bot;cx.fillRect(pad.x+2,pad.y+2,pad.w,PAD_H);
  cx.fillStyle=col;cx.fillRect(pad.x,pad.y,pad.w,PAD_H);
  cx.fillStyle=top;cx.fillRect(pad.x+2,pad.y+2,pad.w-4,3);
  if(pad.pw){
    var mt=pad.pw==='expand'?8:6;
    var ratio=Math.max(0,pad.pt/mt);
    cx.fillStyle='rgba(255,255,255,0.3)';cx.fillRect(pad.x,pad.y+PAD_H+2,pad.w*ratio,3);
  }
}
function updBall(dt){
  if(ball.slowed){ball.st-=dt;if(ball.st<=0){ball.vx/=0.55;ball.vy/=0.55;ball.slowed=false;}}
  ball.trail.push({x:ball.x,y:ball.y});
  if(ball.trail.length>12) ball.trail.shift();
  ball.x+=ball.vx; ball.y+=ball.vy;
  if(ball.x-BALL_R<0){ball.x=BALL_R;ball.vx=Math.abs(ball.vx);}
  if(ball.x+BALL_R>W){ball.x=W-BALL_R;ball.vx=-Math.abs(ball.vx);}
  if(ball.y-BALL_R<0){ball.y=BALL_R;ball.vy=Math.abs(ball.vy);}
  if(ball.y-BALL_R>H) return{destroyed:[],lost:true};
  if(ball.vy>0&&overlap(ball.x-BALL_R,ball.y-BALL_R,BALL_R*2,BALL_R*2,pad.x,pad.y,pad.w,PAD_H)){
    ball.y=pad.y-BALL_R;
    var hr=(ball.x-pad.x)/pad.w;
    var ang=(hr-0.5)*2*65*Math.PI/180;
    var spd=Math.hypot(ball.vx,ball.vy);
    ball.vx=spd*Math.sin(ang); ball.vy=-spd*Math.cos(ang);
    var minVy=spd*0.28;
    if(Math.abs(ball.vy)<minVy){ball.vy=-minVy;ball.vx=Math.sign(ball.vx)*Math.sqrt(Math.max(0,spd*spd-minVy*minVy));}
    combo=0;
  }
  var destroyed=[];
  for(var bi=0;bi<bricks.length;bi++){
    var b=bricks[bi];
    if(!b.alive) continue;
    if(!overlap(ball.x-BALL_R,ball.y-BALL_R,BALL_R*2,BALL_R*2,b.x,b.y,BW,BH)) continue;
    var ol=ball.x+BALL_R-b.x,or2=b.x+BW-(ball.x-BALL_R);
    var ot=ball.y+BALL_R-b.y,ob=b.y+BH-(ball.y-BALL_R);
    var m=Math.min(ol,or2,ot,ob);
    if(m===ot&&ball.vy>0){ball.vy=-Math.abs(ball.vy);ball.y=b.y-BALL_R;}
    else if(m===ob&&ball.vy<0){ball.vy=Math.abs(ball.vy);ball.y=b.y+BH+BALL_R;}
    else if(m===ol&&ball.vx>0){ball.vx=-Math.abs(ball.vx);ball.x=b.x-BALL_R;}
    else{ball.vx=Math.abs(ball.vx);ball.x=b.x+BW+BALL_R;}
    b.ft=0.1;
    if(b.type!=='steel'){b.hp--;if(b.hp<=0){b.alive=false;destroyed.push(b);}}
    break;
  }
  return{destroyed:destroyed,lost:false};
}
function drawBall(){
  var n=ball.trail.length;
  ball.trail.forEach(function(t,i){
    cx.globalAlpha=(i+1)/n*0.7;
    cx.beginPath();cx.arc(t.x,t.y,Math.max(2,BALL_R*(i+1)/n),0,Math.PI*2);
    cx.fillStyle='#88ccff';cx.fill();
  });
  cx.globalAlpha=1;
  cx.beginPath();cx.arc(ball.x+1,ball.y+1,BALL_R,0,Math.PI*2);cx.fillStyle='rgba(0,0,0,0.4)';cx.fill();
  cx.beginPath();cx.arc(ball.x,ball.y,BALL_R,0,Math.PI*2);cx.fillStyle='#e0f0ff';cx.fill();
  cx.beginPath();cx.arc(ball.x-2,ball.y-2,BALL_R*0.4,0,Math.PI*2);cx.fillStyle='#ffffff';cx.fill();
}
function drawBrick(b){
  if(!b.alive) return;
  var c=b.type==='steel'?BCOLORS.steel:(BCOLORS[Math.min(b.hp,5)]||BCOLORS[1]);
  var col=b.ft>0?'#ffffff':c.fill;
  var shine=b.ft>0?'#ffffff':c.shine;
  var shadow=b.ft>0?'#aaaaaa':c.shadow;
  cx.fillStyle=shadow;cx.fillRect(b.x+2,b.y+2,BW,BH);
  cx.fillStyle=col;cx.fillRect(b.x,b.y,BW,BH);
  cx.fillStyle=shine;cx.fillRect(b.x+2,b.y+2,BW-4,4);
  cx.fillStyle='rgba(255,255,255,0.15)';cx.fillRect(b.x+2,b.y+2,2,BH-4);
  if(b.type==='steel'){
    [[b.x+6,b.y+5],[b.x+BW-8,b.y+5],[b.x+6,b.y+BH-7],[b.x+BW-8,b.y+BH-7]].forEach(function(pt){
      cx.fillStyle='#ccdde0';cx.beginPath();cx.arc(pt[0],pt[1],2,0,Math.PI*2);cx.fill();
    });
  }
}
function drawPU(p){
  var PUCOLORS={expand:'#32dc50',slow:'#00dcff',life:'#ff64b4',shrink:'#ff3232'};
  var PULABELS={expand:'+W',slow:'SL',life:'+1',shrink:'-W'};
  var col=PUCOLORS[p.type];
  var r=Math.round(12*(1+0.08*Math.sin(p.anim*6)));
  cx.beginPath();cx.arc(p.x,p.y,r+1,0,Math.PI*2);cx.fillStyle='rgba(0,0,0,0.3)';cx.fill();
  cx.beginPath();cx.arc(p.x,p.y,r,0,Math.PI*2);cx.fillStyle=col;cx.fill();
  cx.fillStyle='white';cx.font='bold 9px monospace';cx.textAlign='center';cx.textBaseline='middle';
  cx.fillText(PULABELS[p.type],p.x,p.y);
}
function drawBG(){
  cx.fillStyle='#000060';cx.fillRect(0,0,W,H);
  cx.strokeStyle='rgba(0,0,100,0.4)';cx.lineWidth=1;
  for(var x=0;x<W;x+=20){cx.beginPath();cx.moveTo(x,0);cx.lineTo(x,H);cx.stroke();}
  for(var y=0;y<H;y+=20){cx.beginPath();cx.moveTo(0,y);cx.lineTo(W,y);cx.stroke();}
}
function menuBtn(x,y,w,h,label){
  cx.fillStyle='#102090';cx.fillRect(x+2,y+2,w,h);
  cx.fillStyle='#3060d0';cx.fillRect(x,y,w,h);
  cx.fillStyle='rgba(255,255,255,0.25)';cx.fillRect(x+2,y+2,w-4,3);
  cx.fillStyle='white';cx.font='bold 20px monospace';cx.textAlign='center';cx.textBaseline='middle';
  cx.fillText(label,x+w/2,y+h/2);
}
function ct(text,font,color,y){
  cx.font=font;cx.fillStyle=color;cx.textAlign='center';cx.textBaseline='top';cx.fillText(text,W/2,y);
}

var last=performance.now();
function loop(ts){
  requestAnimationFrame(loop);
  var dt=Math.min((ts-last)/1000,0.05);last=ts;
  tt+=dt;at+=dt;
  drawBG();

  if(ST==='menu'){
    var grd=cx.createLinearGradient(0,H/2-160,0,H/2-80);
    grd.addColorStop(0,'#ffdd00');grd.addColorStop(1,'#ff8800');
    cx.font='bold 52px monospace';cx.textAlign='center';cx.textBaseline='top';
    cx.fillStyle='rgba(0,0,0,0.5)';cx.fillText('ARKANOID',W/2+3,H/2-158);
    cx.fillStyle=grd;cx.fillText('ARKANOID',W/2,H/2-160);
    cx.fillStyle='#00ccff';cx.font='16px monospace';cx.fillText('.- by midea',W/2,H/2-108);
    ['Jugar','Instrucciones','Creditos'].forEach(function(l,i){menuBtn(W/2-100,H/2-20+i*54,200,40,l);});

  } else if(ST==='instructions'){
    cx.fillStyle='rgba(0,0,40,0.88)';cx.fillRect(20,20,W-40,H-40);
    cx.strokeStyle='#00ccff';cx.lineWidth=2;cx.strokeRect(20,20,W-40,H-40);
    [['INSTRUCCIONES','bold 32px monospace','#ffdd00',35],
     ['Flechas / A D  mover paleta','16px monospace','#fff',90],
     ['ESPACIO  lanzar pelota','16px monospace','#fff',114],
     ['P  pausar / reanudar','16px monospace','#fff',138],
     ['R  reiniciar nivel','16px monospace','#fff',162],
     ['ESC  menu principal','16px monospace','#fff',186],
     ['LADRILLOS','bold 22px monospace','#00ccff',220],
     ['Azul=1  Naranja=2  Rojo=3','16px monospace','#fff',252],
     ['Morado=4  Verde=5  Gris=acero','16px monospace','#fff',276],
     ['ESC para volver','14px monospace','#556',H-70]
    ].forEach(function(a){ct(a[0],a[1],a[2],a[3]);});

  } else if(ST==='credits'){
    cx.fillStyle='rgba(0,0,40,0.88)';cx.fillRect(20,20,W-40,H-40);
    cx.strokeStyle='#ffdd00';cx.lineWidth=2;cx.strokeRect(20,20,W-40,H-40);
    [['CREDITOS','bold 36px monospace','#ffdd00',50],
     ['Proyecto academico','bold 20px monospace','#00ccff',110],
     ['Adaptado en JavaScript Canvas','16px monospace','#fff',145],
     ['Inspirado en Arkanoid (Taito 1986)','16px monospace','#fff',185],
     ['y Breakout (Atari 1976)','16px monospace','#fff',210],
     ['ESC para volver','14px monospace','#556',H-70]
    ].forEach(function(a){ct(a[0],a[1],a[2],a[3]);});

  } else if(['launching','playing','paused','level_complete'].indexOf(ST)>=0){
    bricks.forEach(function(b){if(b.ft>0)b.ft=Math.max(0,b.ft-dt);drawBrick(b);});
    pups.forEach(drawPU);
    drawBall(); drawPad();
    updateHUD();

    if(ST==='launching'){
      ball.x=pad.x+pad.w/2;ball.y=pad.y-BALL_R-1;ball.trail=[];
      cx.fillStyle='rgba(200,220,255,0.85)';cx.font='16px monospace';cx.textAlign='center';cx.textBaseline='bottom';
      cx.fillText('ESPACIO o clic para lanzar',W/2,H-8);
    } else if(ST==='playing'){
      updPad(dt);
      var res=updBall(dt);
      if(res.lost){
        lives--;combo=0;pups=[];updateHUD();
        if(lives<=0){ST='gameover';}
        else{
          pad={x:(W-PAD_BASE)/2,y:PAD_Y,w:PAD_BASE,pw:null,pt:0};
          var spd=4+(lv-1)*0.6;
          var ang=(Math.random()*70-35)*Math.PI/180;
          ball={x:pad.x+PAD_BASE/2,y:pad.y-BALL_R-1,vx:spd*Math.sin(ang),vy:-spd*Math.cos(ang),trail:[],slowed:false,st:0};
          ST='launching';
        }
      } else {
        res.destroyed.forEach(function(b){
          combo++;maxCombo=Math.max(maxCombo,combo);
          var mult=1+Math.floor(combo/3)*0.5;
          score+=Math.round((b.maxHp>10?1:b.maxHp)*50*mult);
          markBingo();
          if(Math.random()<0.28){
            var types=['expand','slow','life','shrink'];
            pups.push({x:b.x+BW/2,y:b.y+BH/2,type:types[Math.floor(Math.random()*4)],active:true,anim:0});
          }
        });
        pups.forEach(function(p){
          p.y+=2;p.anim+=dt;if(p.y>H)p.active=false;
          if(p.active&&overlap(p.x-14,p.y-14,28,28,pad.x,pad.y,pad.w,PAD_H)){
            if(p.type==='expand'||p.type==='shrink') applyPadPU(p.type);
            else if(p.type==='slow'&&!ball.slowed){ball.vx*=0.55;ball.vy*=0.55;ball.slowed=true;ball.st=6;}
            else if(p.type==='life') lives=Math.min(6,lives+1);
            p.active=false;
          }
        });
        pups=pups.filter(function(p){return p.active;});
        updateHUD();
        if(!bricks.some(function(b){return b.alive&&b.type!=='steel';})){ST='level_complete';msgT=2.5;}
      }
    } else if(ST==='level_complete'){
      msgT-=dt;if(msgT<=0){lv++;if(lv>3)ST='victory';else loadLv();}
      cx.fillStyle='rgba(0,0,20,0.7)';cx.fillRect(0,0,W,H);
      ct('NIVEL '+lv+' SUPERADO!','bold 38px monospace','#32dc50',H/2-50);
      ct('Preparando nivel '+(lv+1)+'...','20px monospace','#fff',H/2+10);
    } else if(ST==='paused'){
      cx.fillStyle='rgba(0,0,20,0.7)';cx.fillRect(0,0,W,H);
      ct('PAUSA','bold 48px monospace','#ffdd00',H/2-60);
      ct('P reanudar  R reiniciar  ESC menu','18px monospace','#fff',H/2+10);
    }

  } else if(ST==='gameover'){
    bricks.forEach(function(b){drawBrick(b);});pups.forEach(drawPU);drawBall();drawPad();
    cx.fillStyle='rgba(0,0,10,0.8)';cx.fillRect(0,0,W,H);
    ct('GAME OVER','bold 60px monospace','#ff2040',H/2-120);
    ct('Puntuacion: '+String(score).padStart(7,'0'),'bold 26px monospace','#fff',H/2-30);
    ct('Combo max: x'+maxCombo,'22px monospace','#ffdd00',H/2+4);
    menuBtn(W/2-160,H/2+80,135,40,'Reiniciar');
    menuBtn(W/2+25,H/2+80,135,40,'Menu');
    updateHUD();

  } else if(ST==='victory'){
    bricks.forEach(function(b){drawBrick(b);});pups.forEach(drawPU);drawBall();drawPad();
    cx.fillStyle='rgba(0,0,10,0.8)';cx.fillRect(0,0,W,H);
    var hue=(Math.sin(at*2)+1)/2;
    var rc=Math.round(255*hue),gc2=Math.round(200*(1-hue)+80);
    cx.font='bold 56px monospace';cx.textAlign='center';cx.textBaseline='top';
    cx.fillStyle='rgb('+rc+','+gc2+',50)';cx.fillText('VICTORIA!',W/2,H/2-120);
    ct('Puntuacion: '+String(score).padStart(7,'0'),'bold 26px monospace','#fff',H/2-30);
    ct('Combo max: x'+maxCombo,'22px monospace','#ffdd00',H/2+4);
    menuBtn(W/2-160,H/2+80,135,40,'Reiniciar');
    menuBtn(W/2+25,H/2+80,135,40,'Menu');
    updateHUD();
  }
}
requestAnimationFrame(loop);
updateHUD();
})();
</script>
</body>
</html>
"""

display(HTML(html))