# -*- coding: utf-8 -*-
"""buscaminas1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlySuIaH_I809H333fVv_XKXT-g-G2Ve
"""

# -*- coding: utf-8 -*-
"""BUSCAMINAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yg_cam8E8F3WpqCzcMTBK0JBVWXAqs3
"""

from IPython.display import display, HTML

HTML_JUEGO = """
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: 'Segoe UI', sans-serif;
  background: #1a1a2e;
  color: white;
  padding: 16px;
  min-height: 600px;
}

/* ── MENÚ ── */
#menu {
  max-width: 420px;
  margin: 0 auto;
  text-align: center;
  padding-top: 20px;
}
#menu h1 {
  font-size: 32px;
  font-weight: 800;
  background: linear-gradient(90deg, #f59e0b, #ef4444);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  margin-bottom: 6px;
}
#menu p { color: rgba(255,255,255,0.5); font-size: 13px; margin-bottom: 28px; }

.seccion { margin-bottom: 20px; text-align: left; }
.seccion label { font-size: 12px; color: rgba(255,255,255,0.4); text-transform: uppercase; letter-spacing: 1px; display: block; margin-bottom: 10px; }

.opciones-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; }
.opcion-btn {
  background: rgba(255,255,255,0.07);
  border: 1px solid rgba(255,255,255,0.12);
  border-radius: 10px;
  padding: 12px 8px;
  cursor: pointer;
  color: white;
  font-size: 13px;
  transition: all 0.2s;
  text-align: center;
}
.opcion-btn:hover { background: rgba(245,158,11,0.2); border-color: rgba(245,158,11,0.5); }
.opcion-btn.activo { background: rgba(245,158,11,0.25); border-color: #f59e0b; color: #f59e0b; font-weight: 600; }
.opcion-btn small { display: block; color: rgba(255,255,255,0.4); font-size: 11px; margin-top: 3px; }
.opcion-btn.activo small { color: rgba(245,158,11,0.7); }

.btn-jugar {
  width: 100%;
  background: linear-gradient(90deg, #f59e0b, #ef4444);
  border: none;
  border-radius: 12px;
  color: white;
  font-size: 16px;
  font-weight: 700;
  padding: 16px;
  cursor: pointer;
  margin-top: 8px;
  transition: opacity 0.2s;
}
.btn-jugar:hover { opacity: 0.85; }

/* ── JUEGO ── */
#juego { display: none; }

.topbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: 700px;
  margin: 0 auto 12px;
  gap: 10px;
}
.stat-box {
  background: rgba(255,255,255,0.07);
  border: 1px solid rgba(255,255,255,0.1);
  border-radius: 10px;
  padding: 8px 14px;
  text-align: center;
  min-width: 70px;
}
.stat-box .val { font-size: 20px; font-weight: 700; color: #f59e0b; }
.stat-box .lbl { font-size: 10px; color: rgba(255,255,255,0.4); }

.btns-top { display: flex; gap: 8px; }
.btn-top {
  background: rgba(255,255,255,0.08);
  border: 1px solid rgba(255,255,255,0.12);
  border-radius: 8px;
  color: white;
  font-size: 12px;
  padding: 8px 14px;
  cursor: pointer;
  transition: background 0.2s;
}
.btn-top:hover { background: rgba(255,255,255,0.15); }

/* info de turno */
#turno-info {
  max-width: 700px;
  margin: 0 auto 10px;
  background: rgba(255,255,255,0.06);
  border-radius: 8px;
  padding: 8px 14px;
  font-size: 13px;
  display: none;
}
.p1-color { color: #60a5fa; font-weight: 600; }
.p2-color { color: #f97316; font-weight: 600; }

/* Puntos en modo multi */
#marcador {
  max-width: 700px;
  margin: 0 auto 10px;
  display: none;
  gap: 10px;
}
.marca-card {
  flex: 1;
  border-radius: 10px;
  padding: 10px 14px;
  font-size: 13px;
}
.marca-p1 { background: rgba(96,165,250,0.15); border: 1px solid rgba(96,165,250,0.3); }
.marca-p2 { background: rgba(249,115,22,0.15); border: 1px solid rgba(249,115,22,0.3); }
.marca-card .pts { font-size: 22px; font-weight: 700; }
.marca-p1 .pts { color: #60a5fa; }
.marca-p2 .pts { color: #f97316; }
.marca-card .minas-hit { font-size: 11px; color: rgba(255,255,255,0.4); margin-top: 2px; }

/* Tablero */
#tablero-wrap {
  overflow-x: auto;
  max-width: 100%;
}
#tablero {
  display: inline-grid;
  gap: 2px;
  margin: 0 auto;
  display: block;
}
.fila { display: flex; gap: 2px; margin-bottom: 2px; }

.celda {
  width: 30px;
  height: 30px;
  border-radius: 5px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 13px;
  font-weight: 700;
  cursor: pointer;
  user-select: none;
  transition: background 0.1s, transform 0.1s;
  border: 1px solid rgba(255,255,255,0.08);
  background: rgba(255,255,255,0.1);
}
.celda:hover { background: rgba(255,255,255,0.18); transform: scale(1.05); }
.celda.revelada {
  background: rgba(255,255,255,0.05);
  cursor: default;
  border-color: rgba(255,255,255,0.04);
}
.celda.revelada:hover { transform: none; background: rgba(255,255,255,0.05); }
.celda.mina { background: rgba(239,68,68,0.4) !important; border-color: #ef4444; }
.celda.bandera { background: rgba(245,158,11,0.2); border-color: rgba(245,158,11,0.5); }
.celda.p1-rev { background: rgba(96,165,250,0.12); }
.celda.p2-rev { background: rgba(249,115,22,0.12); }

.n1 { color: #60a5fa; }
.n2 { color: #34d399; }
.n3 { color: #ef4444; }
.n4 { color: #8b5cf6; }
.n5 { color: #f97316; }
.n6 { color: #06b6d4; }
.n7 { color: #ec4899; }
.n8 { color: #9ca3af; }

/* Mensaje final */
#overlay {
  display: none;
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.75);
  z-index: 100;
  align-items: center;
  justify-content: center;
}
#overlay.visible { display: flex; }
.overlay-card {
  background: #1e1e3a;
  border: 1px solid rgba(255,255,255,0.15);
  border-radius: 20px;
  padding: 36px 40px;
  text-align: center;
  max-width: 360px;
  width: 90%;
}
.overlay-card .emoji { font-size: 52px; margin-bottom: 12px; }
.overlay-card h2 { font-size: 22px; margin-bottom: 10px; }
.overlay-card p { color: rgba(255,255,255,0.6); font-size: 14px; margin-bottom: 20px; white-space: pre-line; }
.overlay-card .btns { display: flex; gap: 10px; justify-content: center; }
.btn-overlay {
  background: linear-gradient(90deg, #f59e0b, #ef4444);
  border: none;
  border-radius: 10px;
  color: white;
  font-size: 14px;
  font-weight: 600;
  padding: 12px 22px;
  cursor: pointer;
}
.btn-overlay-sec {
  background: rgba(255,255,255,0.08);
  border: 1px solid rgba(255,255,255,0.15);
  border-radius: 10px;
  color: white;
  font-size: 14px;
  padding: 12px 22px;
  cursor: pointer;
}
</style>
</head>
<body>

<!-- MENÚ -->
<div id="menu">
  <h1>💣 Buscaminas</h1>
  <p>Click izq: revelar &nbsp;|&nbsp; Click der: bandera</p>

  <div class="seccion">
    <label>Modo de juego</label>
    <div class="opciones-grid">
      <button class="opcion-btn activo" onclick="selModo(this,'solo')">
        🧍 Solo
        <small>Clásico</small>
      </button>
      <button class="opcion-btn" onclick="selModo(this,'vs_cpu')">
        🤖 vs CPU
        <small>Turnos</small>
      </button>
      <button class="opcion-btn" onclick="selModo(this,'vs_p2')">
        👥 2 Jugadores
        <small>Turnos</small>
      </button>
    </div>
  </div>

  <div class="seccion">
    <label>Dificultad</label>
    <div class="opciones-grid">
      <button class="opcion-btn activo" onclick="selDif(this,'facil')">
        😊 Fácil
        <small>9×9, 10 minas</small>
      </button>
      <button class="opcion-btn" onclick="selDif(this,'media')">
        😐 Media
        <small>16×16, 40 minas</small>
      </button>
      <button class="opcion-btn" onclick="selDif(this,'dificil')">
        😰 Difícil
        <small>16×30, 99 minas</small>
      </button>
    </div>
  </div>

  <button class="btn-jugar" onclick="iniciarJuego()">⚡ Jugar</button>
</div>

<!-- JUEGO -->
<div id="juego">
  <div class="topbar">
    <div class="stat-box">
      <div class="val" id="stat-minas">10</div>
      <div class="lbl">💣 Minas</div>
    </div>
    <div class="stat-box">
      <div class="val" id="stat-tiempo">0</div>
      <div class="lbl">⏱ Tiempo</div>
    </div>
    <div class="stat-box">
      <div class="val" id="stat-banderas">0</div>
      <div class="lbl">🚩 Banderas</div>
    </div>
    <div class="btns-top">
      <button class="btn-top" onclick="nuevaPartida()">🔄 Nueva</button>
      <button class="btn-top" onclick="irMenu()">🏠 Menú</button>
    </div>
  </div>

  <div id="turno-info"></div>
  <div id="marcador" style="display:none; flex-direction:row;"></div>

  <div id="tablero-wrap">
    <div id="tablero"></div>
  </div>
</div>

<!-- OVERLAY FINAL -->
<div id="overlay">
  <div class="overlay-card">
    <div class="emoji" id="ov-emoji"></div>
    <h2 id="ov-titulo"></h2>
    <p id="ov-msg"></p>
    <div class="btns">
      <button class="btn-overlay" onclick="nuevaPartida()">🔄 Jugar de nuevo</button>
      <button class="btn-overlay-sec" onclick="irMenu()">🏠 Menú</button>
    </div>
  </div>
</div>

<script>
// ── ESTADO GLOBAL ──
const DIFICULTAD = {
  facil:   { filas: 9,  cols: 9,  minas: 10 },
  media:   { filas: 16, cols: 16, minas: 40 },
  dificil: { filas: 16, cols: 30, minas: 99 },
};
const COLORES_NUM = ['','n1','n2','n3','n4','n5','n6','n7','n8'];
const MAX_MINAS_HIT = 3;

let config = { modo: 'solo', dif: 'facil' };
let tablero = [];       // grid de objetos celda
let filas, cols, totalMinas;
let minasColocadas = false;
let juegoActivo = false;
let tiempoSeg = 0;
let intervaloTiempo = null;
let banderas = 0;

// Multijugador
let turnoActual = 0;   // 0 = J1/Humano, 1 = J2/CPU
let puntos = [0, 0];
let minasHit = [0, 0];
let nombres = ['Jugador', 'Computadora'];

// ── MENÚ ──
function selModo(btn, modo) {
  document.querySelectorAll('.seccion:nth-child(1) .opcion-btn').forEach(b => b.classList.remove('activo'));
  btn.classList.add('activo');
  config.modo = modo;
}
function selDif(btn, dif) {
  document.querySelectorAll('.seccion:nth-child(2) .opcion-btn').forEach(b => b.classList.remove('activo'));
  btn.classList.add('activo');
  config.dif = dif;
}

function iniciarJuego() {
  document.getElementById('menu').style.display = 'none';
  document.getElementById('juego').style.display = 'block';
  if (config.modo === 'vs_p2') nombres = ['Jugador 1', 'Jugador 2'];
  else if (config.modo === 'vs_cpu') nombres = ['Jugador', 'Computadora'];
  else nombres = ['Jugador', ''];
  nuevaPartida();
}

function irMenu() {
  clearInterval(intervaloTiempo);
  cerrarOverlay();
  document.getElementById('juego').style.display = 'none';
  document.getElementById('menu').style.display = 'block';
}

// ── TABLERO ──
function crearTablero() {
  const d = DIFICULTAD[config.dif];
  filas = d.filas; cols = d.cols; totalMinas = d.minas;
  tablero = [];
  for (let r = 0; r < filas; r++) {
    tablero[r] = [];
    for (let c = 0; c < cols; c++) {
      tablero[r][c] = { r, c, mina: false, revelada: false, bandera: false, adyacentes: 0, reveladoPor: null };
    }
  }
}

function colocarMinas(safeR, safeC) {
  const zonaSegura = new Set();
  for (let dr = -1; dr <= 1; dr++)
    for (let dc = -1; dc <= 1; dc++) {
      const nr = safeR+dr, nc = safeC+dc;
      if (nr>=0&&nr<filas&&nc>=0&&nc<cols) zonaSegura.add(nr+','+nc);
    }
  const posibles = [];
  for (let r=0;r<filas;r++) for (let c=0;c<cols;c++)
    if (!zonaSegura.has(r+','+c)) posibles.push([r,c]);

  // shuffle
  for (let i = posibles.length-1; i>0; i--) {
    const j = Math.floor(Math.random()*(i+1));
    [posibles[i],posibles[j]] = [posibles[j],posibles[i]];
  }
  const numMinas = Math.min(totalMinas, posibles.length);
  for (let i=0;i<numMinas;i++) {
    const [r,c] = posibles[i];
    tablero[r][c].mina = true;
  }

  // calcular adyacentes
  for (let r=0;r<filas;r++) for (let c=0;c<cols;c++) {
    if (tablero[r][c].mina) continue;
    let cnt = 0;
    vecinos(r,c).forEach(([nr,nc]) => { if (tablero[nr][nc].mina) cnt++; });
    tablero[r][c].adyacentes = cnt;
  }
  minasColocadas = true;
}

function vecinos(r,c) {
  const res = [];
  for (let dr=-1;dr<=1;dr++) for (let dc=-1;dc<=1;dc++) {
    if (dr===0&&dc===0) continue;
    const nr=r+dr,nc=c+dc;
    if (nr>=0&&nr<filas&&nc>=0&&nc<cols) res.push([nr,nc]);
  }
  return res;
}

// ── RENDER ──
function renderTablero() {
  const cont = document.getElementById('tablero');
  cont.innerHTML = '';
  for (let r=0;r<filas;r++) {
    const fila = document.createElement('div');
    fila.className = 'fila';
    for (let c=0;c<cols;c++) {
      const cel = document.createElement('div');
      cel.className = 'celda';
      cel.dataset.r = r; cel.dataset.c = c;
      cel.addEventListener('click', onClic);
      cel.addEventListener('contextmenu', onDerecho);
      actualizarCelda(cel, tablero[r][c]);
      fila.appendChild(cel);
    }
    cont.appendChild(fila);
  }
}

function actualizarCelda(el, cel) {
  el.className = 'celda';
  el.textContent = '';

  if (cel.revelada) {
    el.classList.add('revelada');
    if (cel.mina) { el.classList.add('mina'); el.textContent = '💣'; }
    else if (cel.adyacentes > 0) {
      el.classList.add(COLORES_NUM[cel.adyacentes]);
      el.textContent = cel.adyacentes;
    }
    // color por jugador en multi
    if (!cel.mina && config.modo !== 'solo') {
      if (cel.reveladoPor === 0) el.classList.add('p1-rev');
      else if (cel.reveladoPor === 1) el.classList.add('p2-rev');
    }
  } else if (cel.bandera) {
    el.classList.add('bandera');
    el.textContent = '🚩';
  }
}

function refrescarCelda(r, c) {
  const el = document.querySelector(`.celda[data-r="${r}"][data-c="${c}"]`);
  if (el) actualizarCelda(el, tablero[r][c]);
}

function refrescarTodo() {
  for (let r=0;r<filas;r++) for (let c=0;c<cols;c++) refrescarCelda(r,c);
}

// ── LÓGICA ──
function revelarCelda(r, c, jugador) {
  const cel = tablero[r][c];
  if (cel.revelada || cel.bandera) return { celdas: [], mina: false };

  const reveladas = [];
  if (cel.mina) {
    cel.revelada = true; cel.reveladoPor = jugador;
    reveladas.push([r,c]);
    return { celdas: reveladas, mina: true };
  }

  // BFS cascada
  const stack = [[r,c]]; const vis = new Set();
  while (stack.length) {
    const [cr,cc] = stack.pop();
    const key = cr+','+cc;
    if (vis.has(key)) continue; vis.add(key);
    const cc2 = tablero[cr][cc];
    if (cc2.revelada || cc2.bandera || cc2.mina) continue;
    cc2.revelada = true; cc2.reveladoPor = jugador;
    reveladas.push([cr,cc]);
    if (cc2.adyacentes === 0)
      vecinos(cr,cc).forEach(([nr,nc]) => { if (!vis.has(nr+','+nc)) stack.push([nr,nc]); });
  }
  return { celdas: reveladas, mina: false };
}

function todasReveladas() {
  for (let r=0;r<filas;r++) for (let c=0;c<cols;c++)
    if (!tablero[r][c].mina && !tablero[r][c].revelada) return false;
  return true;
}

function revelarTodasMinas() {
  for (let r=0;r<filas;r++) for (let c=0;c<cols;c++)
    if (tablero[r][c].mina && !tablero[r][c].revelada) { tablero[r][c].revelada = true; refrescarCelda(r,c); }
}

// ── EVENTOS ──
function onClic(e) {
  if (!juegoActivo) return;
  if (config.modo !== 'solo' && turnoActual === 1) return; // turno CPU
  const r = +e.target.dataset.r, c = +e.target.dataset.c;
  if (tablero[r][c].revelada || tablero[r][c].bandera) return;

  if (!minasColocadas) {
    colocarMinas(r, c);
    iniciarTimer();
  }

  procesarJugada(r, c, turnoActual);
}

function onDerecho(e) {
  e.preventDefault();
  if (!juegoActivo) return;
  if (config.modo !== 'solo' && turnoActual === 1) return;
  const r = +e.target.dataset.r, c = +e.target.dataset.c;
  const cel = tablero[r][c];
  if (cel.revelada) return;
  cel.bandera = !cel.bandera;
  banderas += cel.bandera ? 1 : -1;
  refrescarCelda(r, c);
  actualizarStats();
}

function procesarJugada(r, c, jugador) {
  const res = revelarCelda(r, c, jugador);
  res.celdas.forEach(([cr,cc]) => refrescarCelda(cr,cc));

  if (config.modo === 'solo') {
    if (res.mina) { finJuego(false); return; }
    if (todasReveladas()) { finJuego(true); return; }
  } else {
    if (res.mina) {
      minasHit[jugador]++;
      puntos[jugador] = Math.max(0, puntos[jugador] - 2);
    } else {
      puntos[jugador] += res.celdas.length;
    }
    actualizarMarcador();
    if (todasReveladas() || (minasHit[0]>=MAX_MINAS_HIT && minasHit[1]>=MAX_MINAS_HIT)) {
      finJuego(true); return;
    }
    cambiarTurno();
  }
  actualizarStats();
}

function cambiarTurno() {
  turnoActual = 1 - turnoActual;
  actualizarTurno();
  if (config.modo === 'vs_cpu' && turnoActual === 1) {
    setTimeout(turnoIA, 600);
  }
}

function turnoIA() {
  if (!juegoActivo) return;
  if (minasHit[1] >= MAX_MINAS_HIT) { cambiarTurno(); return; }
  const [r, c] = elegirMovIA();
  if (r === null) return;
  procesarJugada(r, c, 1);
}

// ── IA ──
function elegirMovIA() {
  // 1. Celdas seguras deducidas
  const seguras = deducirSeguras();
  if (seguras.length) {
    const [r,c] = seguras[Math.floor(Math.random()*seguras.length)];
    return [r,c];
  }
  // 2. Menor riesgo
  const mejor = menorRiesgo();
  if (mejor) return mejor;
  // 3. Aleatorio
  const libres = [];
  for (let r=0;r<filas;r++) for (let c=0;c<cols;c++)
    if (!tablero[r][c].revelada && !tablero[r][c].bandera) libres.push([r,c]);
  if (!libres.length) return [null,null];
  return libres[Math.floor(Math.random()*libres.length)];
}

function deducirSeguras() {
  const minasDeducidas = new Set();
  for (let r=0;r<filas;r++) for (let c=0;c<cols;c++)
    if (tablero[r][c].bandera) minasDeducidas.add(r+','+c);

  const seguras = new Set();
  let cambio = true;
  while (cambio) {
    cambio = false;
    for (let r=0;r<filas;r++) for (let c=0;c<cols;c++) {
      const cel = tablero[r][c];
      if (!cel.revelada || cel.mina || cel.adyacentes===0) continue;
      const vecs = vecinos(r,c);
      const marcadas = vecs.filter(([nr,nc]) => minasDeducidas.has(nr+','+nc)).length;
      const ocultas = vecs.filter(([nr,nc]) => !tablero[nr][nc].revelada && !minasDeducidas.has(nr+','+nc));
      if (marcadas === cel.adyacentes && ocultas.length)
        ocultas.forEach(([nr,nc]) => seguras.add(nr+','+nc));
      if (marcadas + ocultas.length === cel.adyacentes && ocultas.length)
        ocultas.forEach(([nr,nc]) => { if (!minasDeducidas.has(nr+','+nc)) { minasDeducidas.add(nr+','+nc); cambio=true; } });
    }
  }
  return [...seguras].map(k => k.split(',').map(Number));
}

function menorRiesgo() {
  const libres = [];
  for (let r=0;r<filas;r++) for (let c=0;c<cols;c++)
    if (!tablero[r][c].revelada && !tablero[r][c].bandera) libres.push([r,c]);
  if (!libres.length) return null;

  let minRiesgo = Infinity, mejores = [];
  libres.forEach(([r,c]) => {
    let maxR = 0; let tieneInfo = false;
    vecinos(r,c).forEach(([nr,nc]) => {
      const v = tablero[nr][nc];
      if (!v.revelada || v.mina || v.adyacentes===0) return;
      tieneInfo = true;
      const vv = vecinos(nr,nc);
      const flags = vv.filter(([a,b])=>tablero[a][b].bandera).length;
      const ocultas = vv.filter(([a,b])=>!tablero[a][b].revelada&&!tablero[a][b].bandera).length;
      const rem = v.adyacentes - flags;
      if (ocultas>0&&rem>0) maxR = Math.max(maxR, rem/ocultas);
    });
    const riesgo = tieneInfo ? maxR : (totalMinas / libres.length);
    if (riesgo < minRiesgo) { minRiesgo=riesgo; mejores=[[r,c]]; }
    else if (riesgo === minRiesgo) mejores.push([r,c]);
  });
  return mejores[Math.floor(Math.random()*mejores.length)];
}

// ── UI / STATS ──
function actualizarStats() {
  document.getElementById('stat-minas').textContent = totalMinas;
  document.getElementById('stat-banderas').textContent = banderas;
  document.getElementById('stat-tiempo').textContent = tiempoSeg;
}

function actualizarTurno() {
  if (config.modo === 'solo') return;
  const info = document.getElementById('turno-info');
  const nom = turnoActual===0 ? `<span class="p1-color">${nombres[0]}</span>` : `<span class="p2-color">${nombres[1]}</span>`;
  info.innerHTML = `Turno: ${nom}`;
}

function actualizarMarcador() {
  const marc = document.getElementById('marcador');
  marc.innerHTML = `
    <div class="marca-card marca-p1">
      <div>${nombres[0]}</div>
      <div class="pts">${puntos[0]}</div>
      <div class="minas-hit">💣 ${minasHit[0]}/${MAX_MINAS_HIT}</div>
    </div>
    <div class="marca-card marca-p2">
      <div>${nombres[1]}</div>
      <div class="pts">${puntos[1]}</div>
      <div class="minas-hit">💣 ${minasHit[1]}/${MAX_MINAS_HIT}</div>
    </div>
  `;
}

function iniciarTimer() {
  clearInterval(intervaloTiempo);
  tiempoSeg = 0;
  intervaloTiempo = setInterval(() => {
    tiempoSeg++;
    document.getElementById('stat-tiempo').textContent = tiempoSeg;
  }, 1000);
}

// ── FIN DE JUEGO ──
function finJuego(gano) {
  juegoActivo = false;
  clearInterval(intervaloTiempo);
  revelarTodasMinas();

  let emoji, titulo, msg;

  if (config.modo === 'solo') {
    if (gano) { emoji='🏆'; titulo='¡Ganaste!'; msg=`Tiempo: ${tiempoSeg}s`; }
    else       { emoji='💥'; titulo='¡Boom!';   msg='Pisaste una mina. ¡Inténtalo de nuevo!'; }
  } else {
    emoji = '🏁'; titulo = '¡Juego terminado!';
    const p0 = puntos[0], p1 = puntos[1];
    if (p0 > p1)      msg = `${nombres[0]}: ${p0} pts\n${nombres[1]}: ${p1} pts\n\n🏆 ¡Gana ${nombres[0]}!`;
    else if (p1 > p0) msg = `${nombres[0]}: ${p0} pts\n${nombres[1]}: ${p1} pts\n\n🏆 ¡Gana ${nombres[1]}!`;
    else               msg = `${nombres[0]}: ${p0} pts\n${nombres[1]}: ${p1} pts\n\n🤝 ¡Empate!`;
  }

  document.getElementById('ov-emoji').textContent = emoji;
  document.getElementById('ov-titulo').textContent = titulo;
  document.getElementById('ov-msg').textContent = msg;
  document.getElementById('overlay').classList.add('visible');
}

function cerrarOverlay() { document.getElementById('overlay').classList.remove('visible'); }

// ── NUEVA PARTIDA ──
function nuevaPartida() {
  cerrarOverlay();
  clearInterval(intervaloTiempo);
  tiempoSeg = 0; banderas = 0;
  turnoActual = 0; puntos = [0,0]; minasHit = [0,0];
  minasColocadas = false; juegoActivo = true;

  crearTablero();
  renderTablero();
  actualizarStats();

  const esMulti = config.modo !== 'solo';
  document.getElementById('turno-info').style.display = esMulti ? 'block' : 'none';
  document.getElementById('marcador').style.display = esMulti ? 'flex' : 'none';
  if (esMulti) { actualizarTurno(); actualizarMarcador(); }
}
</script>
</body>
</html>
"""

display(HTML(HTML_JUEGO))