# -*- coding: utf-8 -*-
"""pierdapapeltijera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC203_ByoiWrohTLGQnXeRjUDJl4EkSo
"""

from IPython.display import display, HTML

html_code = """
<style>
  @import url('https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=Space+Mono:wght@400;700&display=swap');
  #game {
    --roca: #E24B4A; --papel: #378ADD; --tijera: #1D9E75;
    --fondo: #0e0e0e; --card: #1a1a1a; --borde: #2e2e2e;
    --texto: #f0ede6; --muted: #888780;
    font-family: 'Space Mono', monospace;
    background: var(--fondo);
    color: var(--texto);
    min-height: 520px;
    padding: 1.5rem 1rem;
    border-radius: 12px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    max-width: 480px;
    margin: auto;
  }
  #game h1 {
    font-family: 'Syne', sans-serif;
    font-size: 22px; font-weight: 800;
    letter-spacing: 2px; text-transform: uppercase;
    color: var(--texto); text-align: center;
  }
  .scores { display: flex; gap: 2rem; align-items: center; }
  .score-box { text-align: center; }
  .score-label { font-size: 10px; color: var(--muted); letter-spacing: 2px; text-transform: uppercase; }
  .score-num { font-family: 'Syne', sans-serif; font-size: 36px; font-weight: 800; line-height: 1; }
  .score-num.tu  { color: var(--papel); }
  .score-num.cpu { color: var(--roca); }
  .vs-divider { font-size: 11px; color: var(--muted); letter-spacing: 1px; }
  .arena { display: flex; gap: 1rem; align-items: center; justify-content: center; width: 100%; }
  .fighter {
    background: var(--card); border: 1px solid var(--borde);
    border-radius: 12px; width: 130px; height: 130px;
    display: flex; flex-direction: column;
    align-items: center; justify-content: center;
    gap: 6px; transition: border-color 0.3s;
  }
  .fighter.win  { border-color: var(--tijera); box-shadow: 0 0 0 2px var(--tijera); }
  .fighter.lose { border-color: var(--roca);   box-shadow: 0 0 0 2px var(--roca); }
  .fighter.draw { border-color: var(--papel);  box-shadow: 0 0 0 2px var(--papel); }
  .fighter-label { font-size: 10px; color: var(--muted); letter-spacing: 2px; text-transform: uppercase; }
  .emoji-big { font-size: 52px; line-height: 1; display: block; transition: transform 0.3s; }
  .emoji-big.shake { animation: shake 0.4s ease; }
  @keyframes shake {
    0%,100% { transform: rotate(0deg); }
    25% { transform: rotate(-15deg) scale(1.2); }
    75% { transform: rotate(15deg) scale(1.2); }
  }
  .vs-label { font-family: 'Syne', sans-serif; font-weight: 800; font-size: 18px; color: var(--muted); }
  .result-msg {
    font-family: 'Syne', sans-serif; font-size: 20px; font-weight: 800;
    letter-spacing: 1px; min-height: 28px; text-align: center; transition: color 0.3s;
  }
  .result-msg.win  { color: var(--tijera); }
  .result-msg.lose { color: var(--roca); }
  .result-msg.draw { color: var(--papel); }
  .choices { display: flex; gap: 0.75rem; justify-content: center; flex-wrap: wrap; }
  .choice-btn {
    background: var(--card); border: 1px solid var(--borde);
    border-radius: 10px; padding: 0.75rem 1.25rem;
    cursor: pointer; display: flex; flex-direction: column;
    align-items: center; gap: 4px; transition: all 0.15s; min-width: 82px;
  }
  .choice-btn:hover { border-color: #555; transform: translateY(-2px); background: #222; }
  .choice-btn:active { transform: scale(0.96); }
  .choice-btn.roca:hover   { border-color: var(--roca); }
  .choice-btn.papel:hover  { border-color: var(--papel); }
  .choice-btn.tijera:hover { border-color: var(--tijera); }
  .choice-emoji { font-size: 28px; line-height: 1; }
  .choice-name  { font-size: 10px; color: var(--muted); letter-spacing: 1px; text-transform: uppercase; }
  .history { display: flex; gap: 4px; min-height: 18px; flex-wrap: wrap; justify-content: center; max-width: 280px; }
  .hist-dot { width: 10px; height: 10px; border-radius: 50%; display: inline-block; }
  .hist-dot.w { background: var(--tijera); }
  .hist-dot.l { background: var(--roca); }
  .hist-dot.d { background: var(--papel); }
  .reset-btn {
    background: transparent; border: 1px solid var(--borde);
    border-radius: 8px; color: var(--muted);
    font-family: 'Space Mono', monospace; font-size: 10px;
    letter-spacing: 1px; padding: 6px 14px; cursor: pointer;
    text-transform: uppercase; transition: all 0.15s;
  }
  .reset-btn:hover { border-color: #555; color: var(--texto); }
  .countdown {
    font-family: 'Syne', sans-serif; font-size: 14px; font-weight: 700;
    color: var(--muted); min-height: 20px; letter-spacing: 2px;
  }
</style>

<div id="game">
  <h1>Piedra · Papel · Tijera</h1>

  <div class="scores">
    <div class="score-box">
      <div class="score-label">Tú</div>
      <div class="score-num tu" id="scoreP">0</div>
    </div>
    <div class="vs-divider">VS</div>
    <div class="score-box">
      <div class="score-label">CPU</div>
      <div class="score-num cpu" id="scoreC">0</div>
    </div>
  </div>

  <div class="arena">
    <div class="fighter" id="fP">
      <span class="fighter-label">Tú</span>
      <span class="emoji-big" id="emojiP">❓</span>
    </div>
    <div class="vs-label">VS</div>
    <div class="fighter" id="fC">
      <span class="fighter-label">CPU</span>
      <span class="emoji-big" id="emojiC">❓</span>
    </div>
  </div>

  <div class="result-msg" id="result">¡Elige tu arma!</div>
  <div class="countdown" id="countdown"></div>

  <div class="choices">
    <button class="choice-btn roca"   onclick="play('roca')">
      <span class="choice-emoji">🪨</span>
      <span class="choice-name">Roca</span>
    </button>
    <button class="choice-btn papel"  onclick="play('papel')">
      <span class="choice-emoji">📄</span>
      <span class="choice-name">Papel</span>
    </button>
    <button class="choice-btn tijera" onclick="play('tijera')">
      <span class="choice-emoji">✂️</span>
      <span class="choice-name">Tijera</span>
    </button>
  </div>

  <div class="history" id="history"></div>
  <button class="reset-btn" onclick="resetGame()">↺ Reiniciar</button>
</div>

<script>
  const emojis   = { roca: '🪨', papel: '📄', tijera: '✂️' };
  const opciones  = ['roca', 'papel', 'tijera'];
  let scores    = { p: 0, c: 0 };
  let historial  = [];
  let jugando    = false;

  function gana(a, b) {
    return (a==='roca'&&b==='tijera') || (a==='papel'&&b==='roca') || (a==='tijera'&&b==='papel');
  }

  function play(choice) {
    if (jugando) return;
    jugando = true;
    const btns = document.querySelectorAll('.choice-btn');
    btns.forEach(b => b.style.pointerEvents = 'none');

    const ep = document.getElementById('emojiP');
    const ec = document.getElementById('emojiC');
    const fP = document.getElementById('fP');
    const fC = document.getElementById('fC');
    const result = document.getElementById('result');
    const cd = document.getElementById('countdown');

    fP.className = 'fighter'; fC.className = 'fighter';
    ep.textContent = '🤜'; ec.textContent = '🤛';

    let count = 3;
    cd.textContent = count + '...';
    const interval = setInterval(() => {
      count--;
      if (count > 0) {
        cd.textContent = count + '...';
        ep.classList.add('shake'); ec.classList.add('shake');
        setTimeout(() => { ep.classList.remove('shake'); ec.classList.remove('shake'); }, 350);
      } else {
        clearInterval(interval);
        cd.textContent = '¡YA!';
        const cpu = opciones[Math.floor(Math.random() * 3)];
        ep.textContent = emojis[choice];
        ec.textContent = emojis[cpu];
        ep.classList.add('shake'); ec.classList.add('shake');
        setTimeout(() => { ep.classList.remove('shake'); ec.classList.remove('shake'); }, 400);

        setTimeout(() => {
          cd.textContent = '';
          let res, cls;
          if (choice === cpu) {
            res = 'Empate — nadie gana'; cls = 'draw';
            fP.className = 'fighter draw'; fC.className = 'fighter draw';
            historial.push('d');
          } else if (gana(choice, cpu)) {
            res = '¡Ganaste! 🏆'; cls = 'win';
            fP.className = 'fighter win'; fC.className = 'fighter lose';
            scores.p++; historial.push('w');
          } else {
            res = 'Perdiste 💀'; cls = 'lose';
            fP.className = 'fighter lose'; fC.className = 'fighter win';
            scores.c++; historial.push('l');
          }
          result.textContent = res;
          result.className = 'result-msg ' + cls;
          document.getElementById('scoreP').textContent = scores.p;
          document.getElementById('scoreC').textContent = scores.c;
          const hist = document.getElementById('history');
          hist.innerHTML = historial.slice(-20).map(h => `<span class="hist-dot ${h}"></span>`).join('');
          btns.forEach(b => b.style.pointerEvents = '');
          jugando = false;
        }, 500);
      }
    }, 700);
  }

  function resetGame() {
    scores = { p: 0, c: 0 }; historial = [];
    document.getElementById('scoreP').textContent = '0';
    document.getElementById('scoreC').textContent = '0';
    document.getElementById('emojiP').textContent = '❓';
    document.getElementById('emojiC').textContent = '❓';
    document.getElementById('result').textContent = '¡Elige tu arma!';
    document.getElementById('result').className = 'result-msg';
    document.getElementById('history').innerHTML = '';
    document.getElementById('countdown').textContent = '';
    document.getElementById('fP').className = 'fighter';
    document.getElementById('fC').className = 'fighter';
  }
</script>
"""

display(HTML(html_code))