# -*- coding: utf-8 -*-
"""juegoprogramacionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgYI8jEYQzfwHpW4f71At3t7BvRvU0Ic
"""

from IPython.display import display, HTML

GAME_HTML = """<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<style>
*{box-sizing:border-box;margin:0;padding:0;user-select:none;-webkit-user-select:none}
html,body{width:100%;height:100%;background:#0a0a1a;overflow:hidden}
#wrapper{width:100%;height:580px;position:relative;background:#0a0a1a;display:flex;flex-direction:column}
#hud{height:46px;background:linear-gradient(180deg,#111,#1a1a2e);border-bottom:2px solid #ffe135;display:flex;align-items:center;justify-content:space-around;padding:0 8px;flex-shrink:0}
.hb{display:flex;flex-direction:column;align-items:center;gap:1px}
.hl{font-size:7px;color:#ffe135;letter-spacing:1px;font-weight:700;text-transform:uppercase;font-family:monospace}
.hv{font-size:13px;color:#fff;font-weight:900;font-family:monospace}
#hud-name{font-size:9px;color:#00ffcc;font-weight:700;text-align:center;font-family:monospace}
#canvas-area{flex:1;position:relative;overflow:hidden}
#gc{position:absolute;top:0;left:0;display:block}
#mc{position:absolute;bottom:8px;left:0;right:0;display:flex;justify-content:space-between;padding:0 12px;pointer-events:none;z-index:5}
.mg{display:flex;gap:6px;pointer-events:all}
.mb{width:50px;height:50px;border-radius:50%;border:2px solid rgba(255,225,53,0.6);background:rgba(0,0,0,0.4);font-size:18px;cursor:pointer;display:flex;align-items:center;justify-content:center;-webkit-tap-highlight-color:transparent;touch-action:none;color:#ffe135;font-weight:900}
.mb:active{background:rgba(255,225,53,0.3)}
#bzap{border-color:rgba(100,180,255,0.8);color:#88ccff;font-size:14px}
.ov{position:absolute;top:0;left:0;width:100%;height:100%;background:rgba(5,3,20,0.96);display:flex;flex-direction:column;align-items:center;justify-content:flex-start;z-index:20;gap:8px;padding:14px;overflow-y:auto}
.ov.off{display:none}
.btn{padding:10px 24px;border:2px solid #ffe135;border-radius:10px;background:linear-gradient(135deg,#ff8800,#ffcc00);font-size:11px;color:#1a0a00;cursor:pointer;font-weight:900;letter-spacing:1px;text-transform:uppercase;transition:all 0.15s;font-family:monospace;flex-shrink:0}
.btn:hover{transform:scale(1.04);box-shadow:0 0 20px rgba(255,200,0,0.5)}
.btn2{background:linear-gradient(135deg,#2d3748,#1a202c);border-color:#4a5568;color:#e2e8f0}
.btn3{background:linear-gradient(135deg,#1a3a6e,#0f2244);border-color:#3b82f6;color:#93c5fd}
#ms{z-index:22}
.map-wrap{width:100%;max-width:500px;display:flex;flex-direction:column;gap:7px}
.map-row{display:flex;align-items:center;gap:12px;background:rgba(255,255,255,0.04);border:1.5px solid rgba(255,255,255,0.1);border-radius:12px;padding:10px 14px;cursor:pointer;transition:all 0.2s}
.map-row:hover:not(.locked){background:rgba(255,225,53,0.08);border-color:rgba(255,225,53,0.5);transform:translateX(5px)}
.map-row.locked{opacity:0.3;cursor:not-allowed;pointer-events:none}
.map-row.done{border-color:#00ff88;background:rgba(0,255,136,0.04)}
.map-row.current{border-color:#ffe135;box-shadow:0 0 14px rgba(255,225,53,0.2)}
.map-icon{font-size:24px;min-width:32px;text-align:center}
.map-info{flex:1}
.map-name{font-size:12px;font-weight:700;color:#f1f5f9;font-family:monospace}
.map-sub{font-size:10px;color:#64748b;margin-top:2px}
.map-diff{font-size:9px;padding:3px 8px;border-radius:20px;font-weight:700;font-family:monospace;white-space:nowrap}
.d1{background:rgba(0,255,136,0.15);color:#00ff88}
.d2{background:rgba(59,130,246,0.2);color:#60a5fa}
.d3{background:rgba(255,225,53,0.15);color:#ffe135}
.d4{background:rgba(255,107,53,0.15);color:#ff6b35}
.d5{background:rgba(168,85,247,0.2);color:#c084fc}
.map-status{font-size:20px;min-width:24px;text-align:center}
#qs{z-index:30}
.qbox{background:linear-gradient(135deg,#0f172a,#1a1a3e);border:2px solid #ffe135;border-radius:14px;padding:16px;max-width:660px;width:100%;max-height:82vh;overflow-y:auto}
.qtag{font-size:8px;color:#ffe135;letter-spacing:2px;font-weight:700;text-transform:uppercase;font-family:monospace;margin-bottom:4px}
.qconcept{font-size:11px;color:#00ffcc;font-weight:700;margin-bottom:7px;font-family:monospace}
.qtext{font-size:13px;font-weight:700;line-height:1.5;color:#f1f5f9;margin-bottom:10px}
.qcode{background:#0d1117;border:1px solid rgba(255,225,53,0.2);border-radius:8px;padding:10px;margin-bottom:10px;font-family:'Courier New',monospace;font-size:11px;line-height:1.7;color:#e2e8f0;overflow-x:auto;white-space:pre}
.qopts{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-bottom:8px}
.qopt{background:rgba(255,255,255,0.05);border:2px solid rgba(255,255,255,0.12);border-radius:10px;padding:9px 11px;font-size:11px;color:#e2e8f0;cursor:pointer;transition:all 0.15s;text-align:left;display:flex;align-items:flex-start;gap:7px}
.qopt:hover:not(:disabled){background:rgba(255,225,53,0.08);border-color:#ffe135}
.qopt:disabled{cursor:default}
.qopt.ok{background:rgba(0,255,136,0.12)!important;border-color:#00ff88!important}
.qopt.bad{background:rgba(255,51,102,0.1)!important;border-color:#ff3366!important}
.okey{min-width:20px;height:20px;background:rgba(168,85,247,0.3);border-radius:5px;font-size:9px;color:#c084fc;display:flex;align-items:center;justify-content:center;font-weight:900;flex-shrink:0;font-family:monospace}
.exp{padding:9px 11px;border-radius:8px;font-size:11px;line-height:1.6;border-left:4px solid;margin-top:7px;display:none}
.exp.show{display:block}
.exp.ok{background:rgba(0,255,136,0.06);border-color:#00ff88;color:#cce}
.exp.bad{background:rgba(255,51,102,0.06);border-color:#ff3366;color:#cce}
.etitle{font-size:9px;letter-spacing:2px;font-weight:900;margin-bottom:5px;text-transform:uppercase;font-family:monospace}
.etitle.ok{color:#00ff88}.etitle.bad{color:#ff3366}
.ecode{background:#0d1117;border-radius:6px;padding:7px;margin-top:6px;font-family:'Courier New',monospace;font-size:11px;line-height:1.6;white-space:pre;color:#e2e8f0;overflow-x:auto}
.fstats{background:rgba(255,255,255,0.04);border:1px solid rgba(255,225,53,0.2);border-radius:10px;padding:11px 16px;min-width:240px;width:100%;max-width:480px}
.sr{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px solid rgba(255,255,255,0.05);font-size:11px}
.sr:last-child{border:none}
.sl{color:#94a3b8;font-family:monospace;font-size:10px;letter-spacing:1px}
.sv{color:#ffe135;font-family:monospace;font-size:10px;font-weight:900}
.stars{font-size:28px;letter-spacing:4px}
.toast-msg{position:absolute;top:54px;left:50%;transform:translateX(-50%);background:rgba(0,0,0,0.9);border:2px solid #ffe135;border-radius:8px;font-size:9px;color:#ffe135;padding:6px 14px;z-index:100;pointer-events:none;white-space:nowrap;font-weight:700;letter-spacing:1px;font-family:monospace;animation:tpop 0.2s ease,tfade 0.3s ease 1.9s forwards}
@keyframes tpop{from{opacity:0;transform:translateX(-50%) scale(0.7)}to{opacity:1;transform:translateX(-50%) scale(1)}}
@keyframes tfade{to{opacity:0}}
@keyframes bounce{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}
.kw{color:#ff79c6}.fn{color:#50fa7b}.st{color:#f1fa8c}.cm{color:#6272a4}.cl{color:#8be9fd}.nm{color:#bd93f9}
#log-overlay{z-index:25}
.log-section{width:100%;max-width:600px}
.log-title-main{font-family:monospace;color:#ffe135;font-size:15px;font-weight:900;letter-spacing:2px;text-align:center;margin-bottom:4px}
.log-subtitle{font-size:10px;color:#64748b;text-align:center;font-family:monospace;margin-bottom:10px}
.log-card{background:rgba(255,255,255,0.03);border:1.5px solid rgba(255,255,255,0.1);border-radius:12px;padding:12px 14px;margin-bottom:8px}
.log-card-header{display:flex;align-items:center;gap:10px;margin-bottom:8px}
.log-card-icon{font-size:20px;min-width:28px}
.log-card-title{font-size:12px;font-weight:700;color:#f1f5f9;font-family:monospace}
.log-card-lvl{font-size:9px;padding:2px 8px;border-radius:20px;font-weight:700;font-family:monospace}
.log-card-body{font-size:10px;color:#94a3b8;line-height:1.7}
.log-card-body b{color:#e2e8f0}
.log-card-body code{background:#0d1117;padding:1px 5px;border-radius:4px;font-family:monospace;color:#8be9fd;font-size:10px}
.log-tip{background:rgba(255,225,53,0.06);border-left:3px solid #ffe135;padding:6px 10px;border-radius:0 6px 6px 0;font-size:10px;color:#ffe135;margin-top:7px;line-height:1.6}
.log-controls{background:rgba(0,255,204,0.05);border:1px solid rgba(0,255,204,0.2);border-radius:8px;padding:8px 12px;margin-bottom:8px}
.log-controls-title{font-size:9px;color:#00ffcc;letter-spacing:2px;font-weight:700;font-family:monospace;margin-bottom:5px}
.log-score-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:6px}
.log-score-item{background:rgba(255,225,53,0.08);border:1px solid rgba(255,225,53,0.2);border-radius:8px;padding:5px 10px;text-align:center;flex:1;min-width:80px}
.log-score-val{font-size:16px;font-weight:900;color:#ffe135;font-family:monospace;display:block}
.log-score-lbl{font-size:9px;color:#64748b;font-family:monospace}
.log-mechanic{display:flex;gap:8px;align-items:flex-start;margin-bottom:5px}
.log-mec-icon{font-size:14px;min-width:20px;margin-top:1px}
.log-mec-text{font-size:10px;color:#94a3b8;line-height:1.6}
.log-mec-text b{color:#e2e8f0}
</style>
</head>
<body>
<div id="wrapper">
  <div id="hud">
    <div class="hb"><span class="hl">VIDAS</span><span class="hv" id="hv">&#x26A1;&#x26A1;&#x26A1;</span></div>
    <div class="hb"><span class="hl">SCORE</span><span class="hv" id="hsc">0</span></div>
    <div id="hud-name">POO QUEST</div>
    <div class="hb"><span class="hl">RAYOS</span><span class="hv" id="hzap">&#x26A1;3</span></div>
    <div class="hb"><span class="hl">MONEDAS</span><span class="hv" id="hco">&#x1FA99;0</span></div>
    <div class="hb"><span class="hl">TIEMPO</span><span class="hv" id="hti">90</span></div>
  </div>
  <div id="canvas-area">
    <canvas id="gc"></canvas>
    <div id="mc">
      <div class="mg">
        <div class="mb" id="bl">&#9664;</div>
        <div class="mb" id="br">&#9654;</div>
      </div>
      <div class="mg">
        <div class="mb" id="bzap">&#9889;</div>
        <div class="mb" id="bj">&#9650;</div>
      </div>
    </div>
  </div>
</div>

<!-- TITLE -->
<div class="ov" id="ts">
  <div style="font-size:50px;animation:bounce 0.9s ease-in-out infinite">&#x26A1;</div>
  <div style="font-family:monospace;color:#ffe135;font-size:24px;font-weight:900;letter-spacing:3px">POO QUEST</div>
  <div style="font-size:10px;color:#94a3b8;text-align:center;max-width:360px;line-height:1.7">
    Ayuda a <strong style="color:#ffe135">Pikachu &#x26A1;</strong> a cruzar <strong style="color:#00ffcc">5 niveles</strong> de POO.<br>
    Llega a la meta &#x2B50; y responde la pregunta de <strong style="color:#c084fc">POO</strong> para avanzar.
  </div>
  <div style="display:flex;gap:8px;flex-wrap:wrap;justify-content:center">
    <button class="btn" id="btn-mapa">&#9654; MAPA DE NIVELES</button>
    <button class="btn btn3" id="btn-log-title">&#x1F4D6; BIT&#xC1;CORA</button>
  </div>
  <div style="background:rgba(0,255,204,0.06);border:1px solid rgba(0,255,204,0.2);border-radius:8px;padding:8px 14px;font-size:10px;color:#94a3b8;text-align:center;font-family:monospace;max-width:380px">
    &#x2190; &#x2192; Mover &nbsp;|&nbsp; &#x2191; / ESPACIO Saltar<br>
    <span style="color:#88ccff">Z / bot&#xF3;n &#9889; = Lanzar RAYO (3 por nivel)</span><br>
    Pisa enemigos desde arriba &nbsp;|&nbsp; Rayo los destruye a distancia
  </div>
</div>

<!-- MAP -->
<div class="ov off" id="ms">
  <div style="font-family:monospace;color:#ffe135;font-size:13px;font-weight:900;letter-spacing:1px;flex-shrink:0">&#x26A1; MAPA DE AVENTURA &#x26A1;</div>
  <div class="map-wrap" id="mg"></div>
  <div style="display:flex;gap:8px;flex-shrink:0">
    <button class="btn btn2" id="btn-mapa-back">&#x2190; T&#xCD;TULO</button>
    <button class="btn btn3" id="btn-log-map">&#x1F4D6; BIT&#xC1;CORA</button>
  </div>
</div>

<!-- QUESTION -->
<div class="ov off" id="qs">
  <div class="qbox">
    <div class="qtag" id="qtag">NIVEL 1</div>
    <div class="qconcept" id="qcon">Concepto</div>
    <div class="qtext" id="qtxt"></div>
    <div class="qcode" id="qcode" style="display:none"></div>
    <div class="qopts" id="qopts"></div>
    <div class="exp" id="qexp"></div>
    <div style="margin-top:10px;text-align:center">
      <button class="btn" id="qnext" style="display:none">SIGUIENTE NIVEL &#x2192;</button>
    </div>
  </div>
</div>

<!-- LEVEL COMPLETE -->
<div class="ov off" id="lc">
  <div style="font-size:44px;animation:bounce 0.7s infinite">&#x2B50;</div>
  <div style="font-family:monospace;color:#ffe135;font-size:18px;font-weight:900">&#xA1;META ALCANZADA!</div>
  <div class="stars" id="lc-stars">&#x2B50;&#x2B50;&#x2B50;</div>
  <div style="font-size:26px;color:#00ffcc;font-weight:900;font-family:monospace" id="lc-xp">+2000 XP</div>
  <div style="color:#94a3b8;font-size:11px;text-align:center">Responde la pregunta de POO para avanzar</div>
  <div style="display:flex;gap:8px">
    <button class="btn" id="btn-showq">VER PREGUNTA &#x26A1;</button>
    <button class="btn btn3" id="btn-log-lc">&#x1F4D6; BIT&#xC1;CORA</button>
  </div>
</div>

<!-- GAME OVER -->
<div class="ov off" id="go">
  <div style="font-size:44px">&#x1F480;</div>
  <div style="font-family:monospace;color:#ff3366;font-size:24px;font-weight:900">GAME OVER</div>
  <div style="color:#94a3b8;font-size:11px;text-align:center">&#xA1;Pikachu cay&#xF3;! No te rindas</div>
  <button class="btn" id="btn-retry">&#x21BA; REINTENTAR</button>
  <button class="btn btn2" id="btn-go-map">&#x1F4CD; MAPA</button>
</div>

<!-- WIN -->
<div class="ov off" id="ws">
  <div style="font-size:48px;animation:bounce 0.8s infinite">&#x1F3C6;</div>
  <div style="font-family:monospace;color:#ffe135;font-size:16px;font-weight:900;text-align:center;line-height:1.4">&#xA1;MISI&#xD3;N COMPLETADA!<br>&#xA1;MAESTRO DE POO!</div>
  <div class="fstats" id="fst"></div>
  <div style="display:flex;gap:8px">
    <button class="btn" id="btn-reset">&#x21BA; JUGAR DE NUEVO</button>
    <button class="btn btn3" id="btn-log-win">&#x1F4D6; BIT&#xC1;CORA</button>
  </div>
</div>

<!-- BITACORA -->
<div class="ov off" id="log-overlay">
  <div class="log-section">
    <div class="log-title-main">&#x1F4D6; BIT&#xC1;CORA POO QUEST</div>
    <div class="log-subtitle">Gu&#xED;a completa del jugador &#x2014; Programaci&#xF3;n Orientada a Objetos</div>

    <div class="log-controls">
      <div class="log-controls-title">&#x1F3AE; CONTROLES</div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:4px">
        <div style="font-size:10px;color:#94a3b8;line-height:1.8">
          <div><span style="color:#ffe135;font-weight:700">&#x2190; &#x2192;</span> &#x2014; Mover a los lados</div>
          <div><span style="color:#ffe135;font-weight:700">&#x2191; / ESPACIO</span> &#x2014; Saltar</div>
          <div><span style="color:#88ccff;font-weight:700">Z / bot&#xF3;n &#9889;</span> &#x2014; Lanzar rayo</div>
        </div>
        <div style="font-size:10px;color:#94a3b8;line-height:1.8">
          <div><span style="color:#ff8888;font-weight:700">Pisa enemigos</span> desde arriba</div>
          <div><span style="color:#88ccff;font-weight:700">Rayo</span> destruye a distancia</div>
          <div><span style="color:#00ffcc;font-weight:700">3 rayos</span> por nivel (se reponen)</div>
        </div>
      </div>
    </div>

    <div class="log-card">
      <div class="log-card-header">
        <div class="log-card-icon">&#x1F3C6;</div>
        <div>
          <div class="log-card-title">Sistema de Puntuaci&#xF3;n</div>
          <div style="font-size:9px;color:#64748b;font-family:monospace">C&#xF3;mo ganar puntos y monedas</div>
        </div>
      </div>
      <div class="log-score-row">
        <div class="log-score-item"><span class="log-score-val">+50</span><span class="log-score-lbl">Moneda</span></div>
        <div class="log-score-item"><span class="log-score-val">+100</span><span class="log-score-lbl">Pisar enemigo</span></div>
        <div class="log-score-item"><span class="log-score-val">+150</span><span class="log-score-lbl">Rayo enemigo</span></div>
        <div class="log-score-item"><span class="log-score-val">+2000</span><span class="log-score-lbl">Pregunta correcta</span></div>
      </div>
      <div class="log-tip">&#x2B50; Estrellas al completar nivel: 3 estrellas si llegas con m&#xE1;s de 60 seg, 2 si quedan 30&#x2013;60 seg, 1 si menos de 30 seg.</div>
    </div>

    <div class="log-card">
      <div class="log-card-header">
        <div class="log-card-icon">&#x26A1;</div>
        <div>
          <div class="log-card-title">Mec&#xE1;nicas del Juego</div>
          <div style="font-size:9px;color:#64748b;font-family:monospace">Reglas, vidas y rayos</div>
        </div>
      </div>
      <div class="log-mechanic">
        <div class="log-mec-icon">&#x1F4A5;</div>
        <div class="log-mec-text"><b>Vidas (3 por nivel):</b> Pierdes una vida si tocas un enemigo de lado/frente o si caes al vac&#xED;o. Al perder las 3 = Game Over.</div>
      </div>
      <div class="log-mechanic">
        <div class="log-mec-icon">&#9889;</div>
        <div class="log-mec-text"><b>Rayos Thunderbolt:</b> Pikachu tiene <b>3 rayos por nivel</b>. El rayo viaja en la direcci&#xF3;n que miras y destruye al primer enemigo. Da <b>+150 puntos</b>. Se recargan al iniciar cada nivel.</div>
      </div>
      <div class="log-mechanic">
        <div class="log-mec-icon">&#x1F47E;</div>
        <div class="log-mec-text"><b>Enemigos (Ghastly):</b> Patrullan de lado a lado. Pisarlos desde arriba (+100 pts) o eliminarlos con rayo (+150 pts). Si los tocas de frente, pierdes una vida.</div>
      </div>
      <div class="log-mechanic">
        <div class="log-mec-icon">&#x1FA99;</div>
        <div class="log-mec-text"><b>Monedas:</b> Flotan animadas en las plataformas. Rec&#xF3;gelas para sumar +50 pts c/u.</div>
      </div>
      <div class="log-mechanic">
        <div class="log-mec-icon">&#x23F1;</div>
        <div class="log-mec-text"><b>Temporizador:</b> Tienes <b>90 segundos</b> por intento. Si se acaba, pierdes una vida. El tiempo afecta la cantidad de estrellas.</div>
      </div>
    </div>

    <div class="log-card" style="border-color:rgba(0,255,136,0.3)">
      <div class="log-card-header">
        <div class="log-card-icon">&#x1F9F1;</div>
        <div style="flex:1">
          <div class="log-card-title">Nivel 1 &#x2014; Clases y Objetos</div>
          <div style="display:flex;align-items:center;gap:6px;margin-top:2px">
            <span class="log-card-lvl d1">F&#xC1;CIL</span>
            <span style="font-size:9px;color:#64748b;font-family:monospace">Plataformas anchas &middot; 3 enemigos</span>
          </div>
        </div>
      </div>
      <div class="log-card-body">
        <b>Concepto POO &#x2014; Clases y Objetos:</b><br>
        Una <b>clase</b> es el molde que define atributos y comportamientos. Un <b>objeto</b> es una instancia concreta de esa clase.<br>
        <code>class Pikachu:</code> &#x2192; define la clase &nbsp;|&nbsp; <code>pika = Pikachu("Pika")</code> &#x2192; crea el objeto<br><br>
        <b>Pregunta:</b> &#xBF;Cu&#xE1;l es la sintaxis correcta para definir una clase en Python?<br>
        <b>Respuesta:</b> <code>class Pikachu:</code> &#x2014; nunca <code>def</code> ni <code>object</code>.
      </div>
      <div class="log-tip">&#x1F4A1; Los enemigos est&#xE1;n separados. Usa rayos solo si el camino est&#xE1; bloqueado. Recoge todas las monedas antes de saltar.</div>
    </div>

    <div class="log-card" style="border-color:rgba(59,130,246,0.3)">
      <div class="log-card-header">
        <div class="log-card-icon">&#x1F512;</div>
        <div style="flex:1">
          <div class="log-card-title">Nivel 2 &#x2014; Encapsulamiento</div>
          <div style="display:flex;align-items:center;gap:6px;margin-top:2px">
            <span class="log-card-lvl d2">MEDIO</span>
            <span style="font-size:9px;color:#64748b;font-family:monospace">Zigzag &middot; huecos medianos &middot; 5 enemigos</span>
          </div>
        </div>
      </div>
      <div class="log-card-body">
        <b>Concepto POO &#x2014; Encapsulamiento:</b><br>
        El doble guion bajo <code>__atributo</code> aplica <b>name mangling</b>, haciendo el atributo privado. Solo se accede mediante m&#xE9;todos.<br>
        <code>self.__hp = 100</code> &#x2192; privado &nbsp;|&nbsp; <code>def get_hp(self): return self.__hp</code> &#x2192; acceso controlado<br><br>
        <b>Pregunta:</b> &#xBF;Qu&#xE9; hace el doble guion bajo <code>__hp</code>?<br>
        <b>Respuesta:</b> Lo hace privado (encapsulamiento).
      </div>
      <div class="log-tip">&#x1F4A1; Los 5 enemigos patrullan plataformas clave. Usa 1&#x2013;2 rayos estrat&#xE9;gicos para despejar el zigzag.</div>
    </div>

    <div class="log-card" style="border-color:rgba(255,225,53,0.3)">
      <div class="log-card-header">
        <div class="log-card-icon">&#x1F9EC;</div>
        <div style="flex:1">
          <div class="log-card-title">Nivel 3 &#x2014; Herencia</div>
          <div style="display:flex;align-items:center;gap:6px;margin-top:2px">
            <span class="log-card-lvl d3">MEDIO-ALTO</span>
            <span style="font-size:9px;color:#64748b;font-family:monospace">M&#xE1;s huecos &middot; enemigos r&#xE1;pidos &middot; 6 enemigos</span>
          </div>
        </div>
      </div>
      <div class="log-card-body">
        <b>Concepto POO &#x2014; Herencia:</b><br>
        La herencia permite que una clase <b>hijo</b> reutilice atributos y m&#xE9;todos de una clase <b>padre</b>.<br>
        <code>class Pikachu(Pokemon):</code> &#x2014; Si la subclase redefine un m&#xE9;todo, lo sobreescribe (override).<br><br>
        <b>Pregunta:</b> &#xBF;Qu&#xE9; imprimir&#xE1; <code>Pikachu().atacar()</code>?<br>
        <b>Respuesta:</b> <code>"&#xA1;Thunderbolt! &#x26A1;"</code> &#x2014; el m&#xE9;todo de la subclase tiene prioridad.
      </div>
      <div class="log-tip">&#x1F4A1; Usa <code>super()</code> para acceder al m&#xE9;todo del padre sin sobreescribirlo. En el juego, usa el rayo para enemigos en plataformas dif&#xED;ciles.</div>
    </div>

    <div class="log-card" style="border-color:rgba(255,107,53,0.3)">
      <div class="log-card-header">
        <div class="log-card-icon">&#x1F3AD;</div>
        <div style="flex:1">
          <div class="log-card-title">Nivel 4 &#x2014; Polimorfismo</div>
          <div style="display:flex;align-items:center;gap:6px;margin-top:2px">
            <span class="log-card-lvl d4">DIF&#xCD;CIL</span>
            <span style="font-size:9px;color:#64748b;font-family:monospace">Plataformas peque&#xF1;as &middot; 8 enemigos</span>
          </div>
        </div>
      </div>
      <div class="log-card-body">
        <b>Concepto POO &#x2014; Polimorfismo:</b><br>
        El polimorfismo permite que distintos objetos respondan diferente al mismo mensaje. Los <b>m&#xE9;todos m&#xE1;gicos</b> son clave:<br>
        <code>__str__</code> &#x2192; define <code>print(obj)</code> &nbsp;|&nbsp; <code>__len__</code> &#x2192; define <code>len(obj)</code> &nbsp;|&nbsp; <code>__add__</code> &#x2192; define <code>obj1 + obj2</code><br><br>
        <b>Pregunta:</b> &#xBF;Qu&#xE9; imprimir&#xE1; <code>print(Pikachu(25))</code> con <code>__str__</code> definido?<br>
        <b>Respuesta:</b> <code>&#x26A1; Pikachu Nv.25</code> &#x2014; no la direcci&#xF3;n de memoria.
      </div>
      <div class="log-tip">&#x1F4A1; Los 3 rayos son insuficientes para 8 enemigos. Pisa desde arriba a los que est&#xE9;n bajo ti. Reserva rayos para plataformas inalcanzables.</div>
    </div>

    <div class="log-card" style="border-color:rgba(168,85,247,0.4)">
      <div class="log-card-header">
        <div class="log-card-icon">&#x1F31F;</div>
        <div style="flex:1">
          <div class="log-card-title">Nivel 5 &#x2014; Abstracci&#xF3;n (BOSS &#x2605;)</div>
          <div style="display:flex;align-items:center;gap:6px;margin-top:2px">
            <span class="log-card-lvl d5">MUY DIF&#xCD;CIL</span>
            <span style="font-size:9px;color:#64748b;font-family:monospace">Plataformas 55px &middot; 9 enemigos</span>
          </div>
        </div>
      </div>
      <div class="log-card-body">
        <b>Concepto POO &#x2014; Abstracci&#xF3;n:</b><br>
        Las <b>clases abstractas</b> usan el m&#xF3;dulo <code>abc</code> y no se pueden instanciar directamente:<br>
        <code>from abc import ABC, abstractmethod</code><br>
        <code>class Pokemon(ABC):</code> &#x2192; no instanciable &nbsp;|&nbsp; <code>@abstractmethod</code> &#x2192; obliga a implementar en subclases<br><br>
        <b>Los 4 Pilares:</b> &#x1F9F1; Encapsulamiento &middot; &#x1F9EC; Herencia &middot; &#x1F3AD; Polimorfismo &middot; &#x1F31F; Abstracci&#xF3;n<br><br>
        <b>Pregunta:</b> &#xBF;Qu&#xE9; ocurre al instanciar directamente una clase ABC?<br>
        <b>Respuesta:</b> <code>TypeError</code> &#x2014; no se puede instanciar una clase abstracta.
      </div>
      <div class="log-tip">&#x1F4A1; BOSS: Memoriza el recorrido antes de lanzarte. Los rayos son vida. Si pierdes 2 vidas, reinicia.</div>
    </div>

    <div class="log-card" style="border-color:rgba(0,255,204,0.3)">
      <div class="log-card-header">
        <div class="log-card-icon">&#x1F4DA;</div>
        <div><div class="log-card-title">Resumen &#x2014; Los 4 Pilares de POO</div></div>
      </div>
      <div class="log-card-body">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:4px">
          <div style="background:rgba(0,255,136,0.06);border:1px solid rgba(0,255,136,0.2);border-radius:8px;padding:8px">
            <div style="color:#00ff88;font-size:10px;font-weight:700;font-family:monospace;margin-bottom:4px">&#x1F9F1; ENCAPSULAMIENTO</div>
            <div style="font-size:9px;color:#94a3b8;line-height:1.6">Ocultar estado interno. Atributos <code>__privados</code>. Acceso mediante m&#xE9;todos p&#xFA;blicos.</div>
          </div>
          <div style="background:rgba(255,225,53,0.06);border:1px solid rgba(255,225,53,0.2);border-radius:8px;padding:8px">
            <div style="color:#ffe135;font-size:10px;font-weight:700;font-family:monospace;margin-bottom:4px">&#x1F9EC; HERENCIA</div>
            <div style="font-size:9px;color:#94a3b8;line-height:1.6">Reutilizar c&#xF3;digo del padre. <code>class Hijo(Padre)</code>. Sobreescribir m&#xE9;todos con override.</div>
          </div>
          <div style="background:rgba(255,107,53,0.06);border:1px solid rgba(255,107,53,0.2);border-radius:8px;padding:8px">
            <div style="color:#ff6b35;font-size:10px;font-weight:700;font-family:monospace;margin-bottom:4px">&#x1F3AD; POLIMORFISMO</div>
            <div style="font-size:9px;color:#94a3b8;line-height:1.6">Mismo m&#xE9;todo, distintos comportamientos. M&#xE9;todos m&#xE1;gicos: <code>__str__</code>, <code>__len__</code>.</div>
          </div>
          <div style="background:rgba(168,85,247,0.06);border:1px solid rgba(168,85,247,0.2);border-radius:8px;padding:8px">
            <div style="color:#c084fc;font-size:10px;font-weight:700;font-family:monospace;margin-bottom:4px">&#x1F31F; ABSTRACCI&#xD3;N</div>
            <div style="font-size:9px;color:#94a3b8;line-height:1.6">Ocultar implementaci&#xF3;n. Clases <code>ABC</code> con <code>@abstractmethod</code>. Contrato obligatorio.</div>
          </div>
        </div>
      </div>
    </div>

    <div style="text-align:center;padding:8px 0 4px">
      <button class="btn" id="btn-log-back">&#x2190; VOLVER AL JUEGO</button>
    </div>
  </div>
</div>

<script>
const QS=[
  {concept:"Clases y Objetos",tag:"NIVEL 1 — CLASES",
   q:"¿Cuál es la sintaxis correcta para definir una clase <b>Pikachu</b> en Python?",
   code:null,
   opts:[{k:"A",t:"<code>class Pikachu:</code>",ok:true},{k:"B",t:"<code>def Pikachu():</code>",ok:false},{k:"C",t:"<code>object Pikachu:</code>",ok:false},{k:"D",t:"<code>new class Pikachu:</code>",ok:false}],
   exp:"En Python usamos <b>class Nombre:</b> para definir una clase. La clase es el <em>molde</em> y el objeto es la instancia creada desde ese molde.",
   ec:'<span class="kw">class</span> <span class="cl">Pikachu</span>:\n    <span class="kw">def</span> <span class="fn">__init__</span>(self, nombre):\n        self.nombre = nombre\n        self.nivel = <span class="nm">1</span>\n\npika = <span class="cl">Pikachu</span>(<span class="st">"Pika"</span>)  <span class="cm"># objeto</span>',
   xp:2000},
  {concept:"Encapsulamiento",tag:"NIVEL 2 — ENCAPSULAMIENTO",
   q:"¿Qué hace el doble guion bajo <code>__hp</code> en esta clase?",
   code:'<span class="kw">class</span> <span class="cl">Pokemon</span>:\n    <span class="kw">def</span> <span class="fn">__init__</span>(self):\n        self.__hp = <span class="nm">100</span>  <span class="cm"># ← ¿qué hace?</span>\n\n    <span class="kw">def</span> <span class="fn">recibir_dano</span>(self, d):\n        self.__hp -= d',
   opts:[{k:"A",t:"Es un atributo público",ok:false},{k:"B",t:"Lo hace privado (encapsulamiento)",ok:true},{k:"C",t:"Es un método especial",ok:false},{k:"D",t:"Solo es convención",ok:false}],
   exp:"El <b>name mangling</b> con __ hace que el atributo sea <em>privado</em>. Esto es <b>Encapsulamiento</b>: proteger los datos internos del objeto.",
   ec:'p = <span class="cl">Pokemon</span>()\np.__hp          <span class="cm"># ❌ AttributeError</span>\np._Pokemon__hp  <span class="cm"># ✅ (no recomendado)</span>\np.<span class="fn">recibir_dano</span>(<span class="nm">20</span>)  <span class="cm"># ✅ manera correcta</span>',
   xp:2000},
  {concept:"Herencia",tag:"NIVEL 3 — HERENCIA",
   q:"¿Qué imprimirá este código?",
   code:'<span class="kw">class</span> <span class="cl">Pokemon</span>:\n    <span class="kw">def</span> <span class="fn">atacar</span>(self):\n        <span class="kw">return</span> <span class="st">"Ataque normal"</span>\n\n<span class="kw">class</span> <span class="cl">Pikachu</span>(<span class="cl">Pokemon</span>):\n    <span class="kw">def</span> <span class="fn">atacar</span>(self):\n        <span class="kw">return</span> <span class="st">"¡Thunderbolt! ⚡"</span>\n\np = <span class="cl">Pikachu</span>()\nprint(p.<span class="fn">atacar</span>())',
   opts:[{k:"A",t:'"Ataque normal"',ok:false},{k:"B",t:'"¡Thunderbolt! ⚡"',ok:true},{k:"C",t:"Error: no puede heredar",ok:false},{k:"D",t:"Imprime ambos",ok:false}],
   exp:'Imprime <b>"¡Thunderbolt! ⚡"</b> porque <code>Pikachu</code> <em>sobreescribe</em> el método de su padre. Combina <b>Herencia</b> y <b>Polimorfismo</b>.',
   ec:'<span class="kw">class</span> <span class="cl">Raichu</span>(<span class="cl">Pikachu</span>):\n    <span class="kw">def</span> <span class="fn">atacar</span>(self):\n        base = <span class="fn">super</span>().<span class="fn">atacar</span>()\n        <span class="kw">return</span> <span class="st">f"{base} + Mega Volt!"</span>',
   xp:2000},
  {concept:"Polimorfismo / __str__",tag:"NIVEL 4 — POLIMORFISMO",
   q:"¿Qué imprimirá <code>print(p)</code>?",
   code:'<span class="kw">class</span> <span class="cl">Pikachu</span>:\n    <span class="kw">def</span> <span class="fn">__init__</span>(self, nivel):\n        self.nivel = nivel\n    <span class="kw">def</span> <span class="fn">__str__</span>(self):\n        <span class="kw">return</span> <span class="st">f"⚡ Pikachu Nv.{self.nivel}"</span>\n\np = <span class="cl">Pikachu</span>(<span class="nm">25</span>)\nprint(p)',
   opts:[{k:"A",t:"&lt;__main__.Pikachu object&gt;",ok:false},{k:"B",t:"⚡ Pikachu Nv.25",ok:true},{k:"C",t:"self.nivel = 25",ok:false},{k:"D",t:"Error: __str__ no existe",ok:false}],
   exp:"El método mágico <code>__str__</code> define cómo se muestra el objeto con <code>print()</code>. Sin él verías la dirección en memoria.",
   ec:'<span class="cm"># Métodos mágicos útiles:</span>\n<span class="fn">__init__</span>  → constructor\n<span class="fn">__str__</span>   → print(obj)\n<span class="fn">__len__</span>   → len(obj)\n<span class="fn">__add__</span>   → obj1 + obj2',
   xp:2000},
  {concept:"Abstracción",tag:"NIVEL 5 — FINAL BOSS ★",
   q:"¿Qué ocurre al intentar instanciar directamente <code>Pokemon</code>?",
   code:'<span class="kw">from</span> abc <span class="kw">import</span> ABC, abstractmethod\n\n<span class="kw">class</span> <span class="cl">Pokemon</span>(ABC):\n    <span class="cm">@abstractmethod</span>\n    <span class="kw">def</span> <span class="fn">atacar</span>(self): <span class="kw">pass</span>\n\n<span class="kw">class</span> <span class="cl">Pikachu</span>(<span class="cl">Pokemon</span>):\n    <span class="kw">def</span> <span class="fn">atacar</span>(self):\n        <span class="kw">return</span> <span class="st">"⚡ Thunderbolt!"</span>\n\np = <span class="cl">Pokemon</span>()  <span class="cm"># ← ¿qué pasa?</span>',
   opts:[{k:"A",t:"Crea un Pokemon vacío",ok:false},{k:"B",t:"TypeError: no se puede instanciar",ok:true},{k:"C",t:"Crea un Pikachu auto.",ok:false},{k:"D",t:"Funciona sin problemas",ok:false}],
   exp:"Python lanza <b>TypeError</b> al instanciar una clase abstracta. Las clases abstractas definen un <em>contrato</em>: las subclases DEBEN implementar los métodos <code>@abstractmethod</code>.",
   ec:'<span class="cm"># Los 4 Pilares de POO:</span>\n<span class="cm"># 🧱 Encapsulamiento → __atributos</span>\n<span class="cm"># 🧬 Herencia       → class Hijo(Padre)</span>\n<span class="cm"># 🎭 Polimorfismo   → override métodos</span>\n<span class="cm"># 🌟 Abstracción    → ABC + @abstractmethod</span>',
   xp:2000}
];

const LEVELS=[
  {name:"Clases y Objetos",icon:"🧱",diff:"FÁCIL",dc:"d1",desc:"Plataformas grandes, pocos enemigos",
   plats:[{x:0,y:300,w:260},{x:310,y:260,w:100},{x:460,y:220,w:90},{x:600,y:270,w:100},{x:750,y:230,w:90},{x:890,y:190,w:100},{x:1040,y:240,w:90},{x:1180,y:280,w:120},{x:1360,y:230,w:100},{x:1520,y:190,w:90},{x:1670,y:250,w:300}],
   enemies:[{x:480,y:0,r:80},{x:760,y:0,r:70},{x:1380,y:0,r:90}],
   coins:[{x:340,y:230},{x:390,y:230},{x:490,y:190},{x:630,y:240},{x:775,y:200},{x:910,y:160},{x:1060,y:210},{x:1380,y:200},{x:1545,y:160}],
   goalX:1920,W:2050},
  {name:"Encapsulamiento",icon:"🔒",diff:"MEDIO",dc:"d2",desc:"Escalera zigzag, más huecos",
   plats:[{x:0,y:300,w:180},{x:240,y:250,w:75},{x:370,y:200,w:75},{x:500,y:155,w:75},{x:630,y:200,w:75},{x:760,y:250,w:75},{x:890,y:195,w:85},{x:1030,y:145,w:75},{x:1160,y:195,w:75},{x:1290,y:245,w:75},{x:1420,y:185,w:85},{x:1560,y:130,w:85},{x:1700,y:185,w:75},{x:1830,y:245,w:260}],
   enemies:[{x:380,y:0,r:55},{x:640,y:0,r:55},{x:900,y:0,r:70},{x:1170,y:0,r:55},{x:1430,y:0,r:70}],
   coins:[{x:260,y:220},{x:390,y:170},{x:520,y:125},{x:650,y:170},{x:780,y:220},{x:910,y:165},{x:1050,y:115},{x:1180,y:165},{x:1440,y:155},{x:1580,y:100}],
   goalX:2040,W:2200},
  {name:"Herencia",icon:"🧬",diff:"MEDIO-ALTO",dc:"d3",desc:"Más huecos, enemigos rápidos",
   plats:[{x:0,y:300,w:160},{x:220,y:255,w:75},{x:360,y:210,w:70},{x:490,y:255,w:70},{x:620,y:210,w:70},{x:750,y:165,w:70},{x:880,y:210,w:70},{x:1010,y:165,w:70},{x:1140,y:120,w:85},{x:1280,y:165,w:70},{x:1410,y:210,w:70},{x:1540,y:165,w:70},{x:1670,y:120,w:70},{x:1800,y:165,w:70},{x:1930,y:235,w:240}],
   enemies:[{x:240,y:0,r:65},{x:510,y:0,r:55},{x:770,y:0,r:55},{x:1030,y:0,r:55},{x:1300,y:0,r:55},{x:1560,y:0,r:55}],
   coins:[{x:245,y:225},{x:378,y:180},{x:508,y:225},{x:638,y:180},{x:768,y:135},{x:898,y:180},{x:1028,y:135},{x:1158,y:90},{x:1675,y:90},{x:1815,y:135}],
   goalX:2120,W:2280},
  {name:"Polimorfismo",icon:"🎭",diff:"DIFÍCIL",dc:"d4",desc:"Plataformas pequeñas, muchos enemigos",
   plats:[{x:0,y:300,w:130},{x:190,y:245,w:65},{x:320,y:195,w:60},{x:450,y:245,w:60},{x:580,y:190,w:60},{x:710,y:145,w:60},{x:840,y:190,w:60},{x:970,y:235,w:60},{x:1100,y:180,w:60},{x:1230,y:130,w:70},{x:1370,y:180,w:60},{x:1500,y:130,w:60},{x:1630,y:175,w:60},{x:1760,y:130,w:60},{x:1890,y:175,w:65},{x:2020,y:245,w:240}],
   enemies:[{x:210,y:0,r:55},{x:470,y:0,r:50},{x:730,y:0,r:55},{x:990,y:0,r:50},{x:1250,y:0,r:50},{x:1520,y:0,r:50},{x:1780,y:0,r:50},{x:2040,y:0,r:55}],
   coins:[{x:210,y:215},{x:340,y:165},{x:470,y:215},{x:600,y:160},{x:730,y:115},{x:860,y:160},{x:990,y:205},{x:1120,y:150},{x:1250,y:100},{x:1520,y:100},{x:1780,y:100}],
   goalX:2210,W:2380},
  {name:"Abstracción (BOSS★)",icon:"🌟",diff:"MUY DIFÍCIL",dc:"d5",desc:"El reto final — ¡sin margen de error!",
   plats:[{x:0,y:300,w:110},{x:170,y:250,w:55},{x:290,y:200,w:55},{x:410,y:250,w:55},{x:530,y:200,w:55},{x:650,y:155,w:55},{x:770,y:200,w:55},{x:890,y:155,w:55},{x:1010,y:200,w:55},{x:1130,y:155,w:55},{x:1250,y:110,w:60},{x:1380,y:155,w:55},{x:1500,y:110,w:55},{x:1620,y:155,w:55},{x:1740,y:110,w:55},{x:1860,y:155,w:55},{x:1980,y:110,w:55},{x:2100,y:155,w:55},{x:2220,y:200,w:55},{x:2340,y:255,w:230}],
   enemies:[{x:190,y:0,r:45},{x:430,y:0,r:45},{x:670,y:0,r:45},{x:910,y:0,r:45},{x:1150,y:0,r:45},{x:1400,y:0,r:45},{x:1640,y:0,r:45},{x:1880,y:0,r:45},{x:2120,y:0,r:45}],
   coins:[{x:190,y:220},{x:310,y:170},{x:430,y:220},{x:550,y:170},{x:670,y:125},{x:790,y:170},{x:910,y:125},{x:1030,y:170},{x:1150,y:125},{x:1270,y:80},{x:1510,y:80},{x:1760,y:80},{x:2000,y:80},{x:2240,y:170}],
   goalX:2525,W:2700}
];

let gs='title',curLvl=0,totalScore=0,totalCoins=0,lives=3,zapCount=3;
let results=[],lvlUnlocked=[true,false,false,false,false],lvlDone=[false,false,false,false,false];
let timer=90,timerInt=null,camX=0,qAnswered=false,logFrom='title';
const canvas=document.getElementById('gc');
const ctx=canvas.getContext('2d');
let CW=0,CH=0,GY=0;
function resize(){const a=document.getElementById('canvas-area');CW=a.clientWidth;CH=a.clientHeight;canvas.width=CW;canvas.height=CH;GY=CH-40;}
resize();
window.addEventListener('resize',()=>{resize();if(gs==='playing')buildLevel(curLvl);});
const PW=32,PH=38;
let P={};
function resetP(){P={x:50,y:200,vx:0,vy:0,onG:false,face:1,ft:0,fr:0,dead:false,inv:0};camX=0;}
let plats=[],enems=[],coins_=[],goal_={},bolts=[];
function buildLevel(li){
  const def=LEVELS[li],off=GY-340;
  plats=def.plats.map(p=>({x:p.x,y:p.y+off,w:p.w,h:16}));
  plats.push({x:-500,y:GY,w:def.W+1000,h:80,ground:true});
  enems=def.enemies.map(e=>{
    const cands=def.plats.filter(p=>e.x>=p.x-10&&e.x<=p.x+p.w+10);
    const pp=cands.length?cands[0]:def.plats[0];
    return {x:e.x,y:pp.y+off-22,sx:e.x,r:e.r,dir:1,vy:0,dead:false,deathAnim:0};
  });
  coins_=def.coins.map(c=>({x:c.x,y:c.y+off,col:false}));
  goal_={x:def.goalX,y:GY-88,reached:false};
  bolts=[];zapCount=3;
  document.getElementById('hzap').textContent='⚡'+zapCount;
  resetP();
}
const K={};
document.addEventListener('keydown',e=>{
  K[e.code]=true;
  if(gs==='playing'&&['Space','ArrowUp','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();
  if(gs==='playing'&&(e.code==='KeyZ'||e.code==='KeyX'))fireBolt();
});
document.addEventListener('keyup',e=>{K[e.code]=false;});
const M={l:false,r:false,j:false,z:false};
function mBtn(id,prop){
  const b=document.getElementById(id);
  b.addEventListener('pointerdown',e=>{M[prop]=true;e.preventDefault();if(prop==='z')fireBolt();},{passive:false});
  ['pointerup','pointerleave','pointercancel'].forEach(ev=>b.addEventListener(ev,()=>{M[prop]=false;}));
}
mBtn('bl','l');mBtn('br','r');mBtn('bj','j');mBtn('bzap','z');
const isL=()=>K.ArrowLeft||K.KeyA||M.l;
const isR=()=>K.ArrowRight||K.KeyD||M.r;
const isJ=()=>K.ArrowUp||K.Space||K.KeyW||M.j;
let jh=false;
const GRAV=0.52,JF=-12.5,SPD=4.2,BOLT_SPD=10;
let zapCooldown=0;
function fireBolt(){
  if(zapCount<=0||P.dead||zapCooldown>0)return;
  zapCount--;zapCooldown=18;
  document.getElementById('hzap').textContent='⚡'+zapCount;
  bolts.push({x:P.face>0?P.x+PW:P.x,y:P.y+PH/2-4,vx:P.face*BOLT_SPD,life:80,hit:false,sparks:[]});
  toast('⚡ Thunderbolt!');
}
function updateBolts(){
  if(zapCooldown>0)zapCooldown--;
  for(let i=bolts.length-1;i>=0;i--){
    const b=bolts[i];
    if(b.hit){b.life-=3;if(b.life<=0)bolts.splice(i,1);continue;}
    b.x+=b.vx;b.life--;
    if(b.life<=0){bolts.splice(i,1);continue;}
    for(const e of enems){
      if(e.dead)continue;
      if(Math.abs(b.x-(e.x+11))<20&&Math.abs(b.y-(e.y+11))<18){
        e.dead=true;e.deathAnim=20;b.hit=true;b.life=15;
        totalScore+=150;document.getElementById('hsc').textContent=totalScore;
        for(let s=0;s<8;s++)b.sparks.push({x:b.x,y:b.y,vx:(Math.random()-0.5)*6,vy:(Math.random()-0.5)*6,life:12});
        toast('+150 ⚡ ¡Thunderbolt!');break;
      }
    }
    if(b.x<camX-50||b.x>camX+CW+50)bolts.splice(i,1);
  }
}
function updateP(){
  if(P.dead){P.vy+=GRAV;P.y+=P.vy;return;}
  if(isL()){P.vx=-SPD;P.face=-1;}else if(isR()){P.vx=SPD;P.face=1;}else P.vx*=0.8;
  if(isJ()&&P.onG&&!jh){P.vy=JF;P.onG=false;jh=true;}
  if(!isJ())jh=false;
  P.vy+=GRAV;P.x+=P.vx;P.y+=P.vy;P.onG=false;
  for(const p of plats){
    if(P.x+PW>p.x&&P.x<p.x+p.w&&P.y+PH>p.y&&P.y+PH<p.y+p.h+14&&P.vy>=0){P.y=p.y-PH;P.vy=0;P.onG=true;}
  }
  if(P.y>GY+200)killP();
  if(P.inv>0)P.inv--;
  camX=Math.max(0,P.x-CW*0.38);
  P.ft++;if(P.ft>=8){P.fr=(P.fr+1)%4;P.ft=0;}
}
function updateE(){
  enems.forEach(e=>{
    if(e.dead){if(e.deathAnim>0)e.deathAnim--;return;}
    e.vy+=GRAV;e.x+=e.dir*1.5;
    if(e.x<e.sx-e.r||e.x>e.sx+e.r)e.dir*=-1;
    for(const p of plats){
      if(e.x+20>p.x&&e.x<p.x+p.w&&e.y+22>p.y&&e.y+22<p.y+p.h+14&&e.vy>=0){e.y=p.y-22;e.vy=0;}
    }
    e.y+=e.vy;
    if(!P.dead&&P.inv===0){
      const dx=Math.abs(P.x+PW/2-(e.x+10)),dy=Math.abs(P.y+PH/2-(e.y+11));
      if(dx<26&&dy<26){
        if(P.vy>1&&P.y+PH<e.y+14){e.dead=true;e.deathAnim=20;P.vy=-10;totalScore+=100;document.getElementById('hsc').textContent=totalScore;toast('+100 PTS ⚡');}
        else killP();
      }
    }
  });
}
function updateC(){
  coins_.forEach(c=>{
    if(c.col)return;
    if(P.x+PW>c.x-8&&P.x<c.x+20&&P.y+PH>c.y-8&&P.y<c.y+20){
      c.col=true;totalScore+=50;totalCoins++;
      document.getElementById('hsc').textContent=totalScore;
      document.getElementById('hco').textContent='🪙'+totalCoins;
    }
  });
}
function checkGoal(){
  if(goal_.reached||P.dead)return;
  if(P.x+PW>goal_.x-28){
    goal_.reached=true;clearInterval(timerInt);gs='levelcomplete';
    const st=timer>60?3:timer>30?2:1;
    document.getElementById('lc-stars').textContent='⭐'.repeat(st)+'☆'.repeat(3-st);
    document.getElementById('lc-xp').textContent='+'+QS[curLvl].xp+' XP';
    show('lc');
  }
}
function killP(){
  if(P.dead)return;
  P.dead=true;P.vy=-8;lives--;updateLives();clearInterval(timerInt);
  setTimeout(()=>{if(lives<=0){gs='gameover';show('go');}else{buildLevel(curLvl);gs='playing';startTimer();}},1200);
}
function updateLives(){
  const el=document.getElementById('hv');
  el.innerHTML='⚡'.repeat(Math.max(0,lives))+'<span style="opacity:.2">⚡</span>'.repeat(Math.max(0,3-lives));
}
function startTimer(){
  clearInterval(timerInt);timer=90;document.getElementById('hti').textContent=timer;
  timerInt=setInterval(()=>{if(gs!=='playing')return;timer--;document.getElementById('hti').textContent=timer;if(timer<=0)killP();},1000);
}
const SKIES=[['#0f1535','#162244'],['#1a0a2e','#2d0a4a'],['#0a1a0a','#0d2e0d'],['#1a0a00','#2e1a00'],['#1a0a1a','#2e0a2e']];
const GROUNDS=['#2d4a1e','#1a0a3a','#143514','#2e1a00','#2e0a2e'];
const PLATCOLORS=[['#3a7a22','#5aaa3a'],['#1a3a7a','#2a5aaa'],['#5a5a1a','#8a8a2a'],['#7a3a1a','#aa5a2a'],['#4a1a7a','#7a2aaa']];
function drawBG(){
  const sk=SKIES[curLvl],g=ctx.createLinearGradient(0,0,0,CH);
  g.addColorStop(0,sk[0]);g.addColorStop(1,sk[1]);
  ctx.fillStyle=g;ctx.fillRect(0,0,CW,CH);
  ctx.fillStyle='rgba(255,255,255,0.5)';
  for(let i=0;i<60;i++){const sx=((i*137+i*i*3)%2000-camX*0.04+2000)%CW,sy=(i*83+17)%170;ctx.beginPath();ctx.arc(sx,sy,i%3?0.6:1.2,0,Math.PI*2);ctx.fill();}
  const gc2=ctx.createLinearGradient(0,GY,0,CH);
  gc2.addColorStop(0,GROUNDS[curLvl]);gc2.addColorStop(1,'#050310');
  ctx.fillStyle=gc2;ctx.fillRect(0,GY,CW,CH-GY);
  ctx.fillStyle=lighten(GROUNDS[curLvl],25);ctx.fillRect(0,GY,CW,4);
}
function lighten(h,a){const n=parseInt(h.slice(1),16);return 'rgb('+Math.min(255,((n>>16)&255)+a)+','+Math.min(255,((n>>8)&255)+a)+','+Math.min(255,(n&255)+a)+')';}
function drawPlats(){
  const [pc1,pc2]=PLATCOLORS[curLvl];
  plats.forEach(p=>{
    if(p.ground)return;
    const x=p.x-camX,y=p.y;
    ctx.fillStyle=pc1;ctx.fillRect(x,y,p.w,p.h);
    ctx.fillStyle=pc2;ctx.fillRect(x+2,y+2,p.w-4,4);
    ctx.strokeStyle='rgba(0,0,0,0.2)';ctx.lineWidth=1;
    for(let bx=x+24;bx<x+p.w;bx+=28){ctx.beginPath();ctx.moveTo(bx,y+3);ctx.lineTo(bx,y+p.h);ctx.stroke();}
  });
}
function drawGoal(){
  const x=goal_.x-camX,y=GY,t=Date.now()/350;
  ctx.fillStyle='#aaa';ctx.fillRect(x-2,y-96,4,96);
  ctx.fillStyle='hsl('+(t*60%360)+',80%,55%)';
  ctx.beginPath();ctx.moveTo(x+3,y-94);ctx.lineTo(x+32,y-82);ctx.lineTo(x+3,y-70);ctx.closePath();ctx.fill();
  ctx.save();ctx.font='22px serif';ctx.textAlign='center';
  ctx.fillStyle='#ffe135';ctx.shadowColor='#ffe135';ctx.shadowBlur=16;
  ctx.fillText('⭐',x,y-100+Math.sin(t)*5);ctx.shadowBlur=0;ctx.restore();
}
function drawEnemy(e){
  const x=e.x-camX,y=e.y;
  if(e.dead){
    if(e.deathAnim>0){
      ctx.save();ctx.globalAlpha=e.deathAnim/20;ctx.translate(x+11,y+11);
      for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.strokeStyle='#ffaa00';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(a)*14,Math.sin(a)*14);ctx.stroke();}
      ctx.restore();
    }
    return;
  }
  ctx.fillStyle='#cc2222';ctx.beginPath();ctx.ellipse(x+11,y+11,11,11,0,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#881111';ctx.beginPath();ctx.ellipse(x+11,y+7,7,7,0,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#ff8800';ctx.beginPath();ctx.arc(x+8,y+5,2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+14,y+5,2,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#000';ctx.beginPath();ctx.arc(x+8,y+5,1,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+14,y+5,1,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#cc2222';ctx.beginPath();ctx.ellipse(x+6,y+20,4,4,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(x+16,y+20,4,4,0,0,Math.PI*2);ctx.fill();
}
function drawBolts(){
  const t=Date.now();
  bolts.forEach(b=>{
    const bx=b.x-camX;
    if(b.hit){
      b.sparks.forEach(s=>{s.x+=s.vx;s.y+=s.vy;s.life--;if(s.life<=0)return;ctx.save();ctx.globalAlpha=s.life/12;ctx.fillStyle='#ffe135';ctx.beginPath();ctx.arc(s.x-camX,s.y,2,0,Math.PI*2);ctx.fill();ctx.restore();});
      return;
    }
    ctx.save();ctx.globalAlpha=0.95;
    const len=b.vx>0?28:-28;
    const grad=ctx.createLinearGradient(bx,b.y,bx+len,b.y);
    grad.addColorStop(0,'rgba(150,220,255,0)');grad.addColorStop(0.4,'rgba(100,180,255,0.9)');grad.addColorStop(1,'rgba(255,255,150,1)');
    ctx.strokeStyle=grad;ctx.lineWidth=3;ctx.shadowColor='#88ccff';ctx.shadowBlur=8;
    const zz=Math.sin(t*0.05)*2;
    ctx.beginPath();ctx.moveTo(bx+len,b.y+zz);ctx.lineTo(bx+len*0.5,b.y-zz);ctx.lineTo(bx,b.y+zz);ctx.stroke();
    ctx.shadowBlur=0;ctx.fillStyle='#ffffff';ctx.beginPath();ctx.arc(bx,b.y,3,0,Math.PI*2);ctx.fill();
    ctx.restore();
  });
}
function drawCoin(c){
  if(c.col)return;
  const t=Date.now()/300,x=c.x-camX,y=c.y+Math.sin(t+c.x*0.01)*3-5;
  ctx.save();ctx.fillStyle='#ffe135';ctx.beginPath();ctx.arc(x+9,y+9,9,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#c8a000';ctx.font='bold 10px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('$',x+9,y+10);ctx.restore();
}
function drawPika(){
  const x=P.x-camX,y=P.y;
  if(P.inv>0&&Math.floor(P.inv/4)%2===1)return;
  ctx.save();ctx.translate(x+PW/2,y+PH/2);
  if(P.face<0)ctx.scale(-1,1);
  if(P.dead)ctx.rotate(Math.PI);
  const bob=(P.fr%2===0&&!P.dead)?-1.5:0;
  const walking=Math.abs(P.vx)>0.5&&P.onG;
  const legSwing=walking?Math.sin(P.ft*0.6)*5:0;
  ctx.save();ctx.translate(11,-1+bob);ctx.rotate(0.45+Math.sin(P.ft*0.4)*0.15);
  ctx.fillStyle='#ffe135';ctx.strokeStyle='#c8a000';ctx.lineWidth=1;
  ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(7,-5);ctx.lineTo(5,-4);ctx.lineTo(10,-12);ctx.lineTo(7,-10);ctx.lineTo(12,-19);ctx.lineTo(9,-16);ctx.lineTo(7,-8);ctx.lineTo(11,-9);ctx.lineTo(4,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();
  ctx.fillStyle='#ffe135';ctx.strokeStyle='#c8a000';ctx.lineWidth=1;
  ctx.beginPath();ctx.ellipse(0,5+bob,12,11,0,0,Math.PI*2);ctx.fill();ctx.stroke();
  ctx.fillStyle='#fffacc';ctx.beginPath();ctx.ellipse(0,8+bob,6.5,5.5,0,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#8B4513';ctx.fillRect(-8,-2+bob,4,4);ctx.fillRect(4,-2+bob,4,4);
  ctx.fillStyle='#ffe135';ctx.strokeStyle='#c8a000';ctx.lineWidth=1;
  ctx.beginPath();ctx.ellipse(-5,14+bob+legSwing,4,6,-0.25,0,Math.PI*2);ctx.fill();ctx.stroke();
  ctx.beginPath();ctx.ellipse(5,14+bob-legSwing,4,6,0.25,0,Math.PI*2);ctx.fill();ctx.stroke();
  const armS=walking?Math.sin(P.ft*0.6)*4:0;
  ctx.beginPath();ctx.ellipse(-13,2+bob+armS,3,5,-0.4,0,Math.PI*2);ctx.fill();ctx.stroke();
  ctx.beginPath();ctx.ellipse(13,2+bob-armS,3,5,0.4,0,Math.PI*2);ctx.fill();ctx.stroke();
  ctx.fillStyle='#ffe135';ctx.beginPath();ctx.ellipse(0,-10+bob,13,12,0,0,Math.PI*2);ctx.fill();ctx.stroke();
  ctx.fillStyle='#ffe135';
  ctx.beginPath();ctx.moveTo(-9,-18+bob);ctx.lineTo(-15,-35+bob);ctx.lineTo(-3,-20+bob);ctx.closePath();ctx.fill();ctx.stroke();
  ctx.fillStyle='#111';ctx.beginPath();ctx.moveTo(-9,-20+bob);ctx.lineTo(-13,-31+bob);ctx.lineTo(-5,-21+bob);ctx.closePath();ctx.fill();
  ctx.fillStyle='#ffe135';ctx.beginPath();ctx.moveTo(9,-18+bob);ctx.lineTo(15,-35+bob);ctx.lineTo(3,-20+bob);ctx.closePath();ctx.fill();ctx.stroke();
  ctx.fillStyle='#111';ctx.beginPath();ctx.moveTo(9,-20+bob);ctx.lineTo(13,-31+bob);ctx.lineTo(5,-21+bob);ctx.closePath();ctx.fill();
  ctx.fillStyle='#111';ctx.beginPath();ctx.arc(-5,-12+bob,3,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(5,-12+bob,3,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-4,-13+bob,1.1,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(6,-13+bob,1.1,0,Math.PI*2);ctx.fill();
  ctx.globalAlpha=0.85;ctx.fillStyle='#ff5555';
  ctx.beginPath();ctx.ellipse(-10,-8+bob,4,3,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(10,-8+bob,4,3,0,0,Math.PI*2);ctx.fill();
  ctx.globalAlpha=1;ctx.fillStyle='#8B4513';ctx.beginPath();ctx.ellipse(0,-7+bob,2,1.5,0,0,Math.PI*2);ctx.fill();
  ctx.strokeStyle='#8B4513';ctx.lineWidth=1.5;
  ctx.beginPath();if(!P.dead)ctx.arc(0,-4+bob,3.5,0.2,Math.PI-0.2);else ctx.arc(0,1+bob,3.5,Math.PI+0.2,-0.2);ctx.stroke();
  if(Math.abs(P.vx)>3&&P.onG){
    ctx.strokeStyle='rgba(255,255,100,0.7)';ctx.lineWidth=1.5;
    for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo((i-1)*7,16+bob);ctx.lineTo((i-1)*7+4,21+bob);ctx.lineTo((i-1)*7+2,25+bob);ctx.stroke();}
  }
  ctx.restore();
}
function loop(){
  requestAnimationFrame(loop);ctx.clearRect(0,0,CW,CH);
  if(gs==='playing'){
    drawBG();drawPlats();enems.forEach(drawEnemy);coins_.forEach(drawCoin);drawGoal();drawBolts();drawPika();
    if(!P.dead){updateP();updateE();updateC();updateBolts();checkGoal();}else{updateP();updateBolts();}
  }else{ctx.fillStyle='#0a0a1a';ctx.fillRect(0,0,CW,CH);}
}
function show(id){document.getElementById(id).classList.remove('off');}
function hide(id){document.getElementById(id).classList.add('off');}
function hideAll(){['ts','ms','lc','go','ws','qs','log-overlay'].forEach(hide);}
function toast(msg){
  const t=document.createElement('div');t.className='toast-msg';t.textContent=msg;
  document.getElementById('canvas-area').appendChild(t);setTimeout(()=>t.remove(),2200);
}
function openLog(from){logFrom=from||'title';hideAll();show('log-overlay');}
function closeLog(){
  hideAll();
  if(logFrom==='map')openMap();
  else if(logFrom==='lc')show('lc');
  else if(logFrom==='win')show('ws');
  else show('ts');
}
function openMap(){hideAll();gs='map';buildMapUI();show('ms');}
function buildMapUI(){
  const mg=document.getElementById('mg');mg.innerHTML='';
  LEVELS.forEach((lv,i)=>{
    const row=document.createElement('div');row.className='map-row';
    if(!lvlUnlocked[i])row.classList.add('locked');
    else if(lvlDone[i])row.classList.add('done');
    else row.classList.add('current');
    const status=!lvlUnlocked[i]?'🔐':lvlDone[i]?'✅':'▶';
    const res=results[i],qmark=res?(res.ok?'✅':'❌'):'❓';
    row.innerHTML='<div class="map-icon">'+lv.icon+'</div><div class="map-info"><div class="map-name">N'+(i+1)+': '+lv.name+'</div><div class="map-sub">'+lv.desc+' · Q: '+qmark+'</div></div><span class="map-diff '+lv.dc+'">'+lv.diff+'</span><div class="map-status">'+status+'</div>';
    if(lvlUnlocked[i])row.addEventListener('click',()=>startLevel(i));
    mg.appendChild(row);
  });
}
function startLevel(i){
  hideAll();curLvl=i;lives=3;updateLives();
  document.getElementById('hud-name').textContent=LEVELS[i].name;
  buildLevel(i);gs='playing';startTimer();
}
function showQ(){
  hide('lc');show('qs');gs='question';
  const q=QS[curLvl];
  document.getElementById('qtag').textContent=q.tag;
  document.getElementById('qcon').textContent=q.concept;
  document.getElementById('qtxt').innerHTML=q.q;
  const ce=document.getElementById('qcode');
  if(q.code){ce.innerHTML=q.code;ce.style.display='block';}else ce.style.display='none';
  const oe=document.getElementById('qopts');oe.innerHTML='';
  q.opts.forEach(o=>{
    const b=document.createElement('button');b.className='qopt';
    b.innerHTML='<span class="okey">'+o.k+'</span><span>'+o.t+'</span>';
    b.addEventListener('click',()=>answerQ(b,o.ok,q));oe.appendChild(b);
  });
  document.getElementById('qexp').className='exp';document.getElementById('qexp').innerHTML='';
  document.getElementById('qnext').style.display='none';qAnswered=false;
}
function answerQ(btn,ok,q){
  if(qAnswered)return;qAnswered=true;
  document.querySelectorAll('.qopt').forEach(b=>b.disabled=true);
  document.querySelectorAll('.qopt').forEach(b=>{const key=b.querySelector('.okey').textContent;if(q.opts.find(o=>o.k===key&&o.ok))b.classList.add('ok');});
  const exp=document.getElementById('qexp');
  if(ok){
    btn.classList.add('ok');totalScore+=q.xp;results[curLvl]={ok:true};
    document.getElementById('hsc').textContent=totalScore;
    exp.className='exp ok show';exp.innerHTML='<div class="etitle ok">✨ ¡CORRECTO! +'+q.xp+' XP</div>'+q.exp+'<div class="ecode">'+q.ec+'</div>';
    toast('⚡ +'+q.xp+' XP ¡Excelente!');
  }else{
    btn.classList.add('bad');results[curLvl]={ok:false};
    exp.className='exp bad show';exp.innerHTML='<div class="etitle bad">💡 ¡Casi! Aprende esto:</div>'+q.exp+'<div class="ecode">'+q.ec+'</div>';
    toast('💡 ¡Lee la explicación!');
  }
  document.getElementById('qnext').style.display='block';
}
function afterQ(){
  hide('qs');lvlDone[curLvl]=true;
  if(curLvl+1<LEVELS.length)lvlUnlocked[curLvl+1]=true;
  const next=curLvl+1;
  if(next>=LEVELS.length)showWin();else{curLvl=next;openMap();}
}
function retryLevel(){hide('go');lives=3;updateLives();startLevel(curLvl);}
function showWin(){
  gs='win';hideAll();show('ws');
  const ok=results.filter(r=>r&&r.ok).length;
  const concs=['🧱 Clases','🔒 Encapsulamiento','🧬 Herencia','🎭 Polimorfismo','🌟 Abstracción'];
  document.getElementById('fst').innerHTML=
    '<div class="sr"><span class="sl">PUNTUACIÓN FINAL</span><span class="sv">'+totalScore+' XP</span></div>'+
    '<div class="sr"><span class="sl">MONEDAS</span><span class="sv">🪙 '+totalCoins+'</span></div>'+
    '<div class="sr"><span class="sl">PREGUNTAS CORRECTAS</span><span class="sv">'+ok+' / 5</span></div>'+
    concs.map((c,i)=>'<div class="sr"><span class="sl">'+c+'</span><span class="sv">'+(results[i]&&results[i].ok?'✅':'❌')+'</span></div>').join('');
}
function resetGame(){
  totalScore=0;totalCoins=0;lives=3;results=[];zapCount=3;
  lvlUnlocked=[true,false,false,false,false];lvlDone=[false,false,false,false,false];curLvl=0;
  document.getElementById('hsc').textContent='0';document.getElementById('hco').textContent='🪙0';document.getElementById('hzap').textContent='⚡3';
  updateLives();openMap();
}
document.getElementById('btn-mapa').addEventListener('click',openMap);
document.getElementById('btn-mapa-back').addEventListener('click',()=>{hideAll();show('ts');});
document.getElementById('btn-showq').addEventListener('click',showQ);
document.getElementById('btn-retry').addEventListener('click',retryLevel);
document.getElementById('btn-go-map').addEventListener('click',openMap);
document.getElementById('btn-reset').addEventListener('click',resetGame);
document.getElementById('qnext').addEventListener('click',afterQ);
document.getElementById('btn-log-title').addEventListener('click',()=>openLog('title'));
document.getElementById('btn-log-map').addEventListener('click',()=>openLog('map'));
document.getElementById('btn-log-lc').addEventListener('click',()=>openLog('lc'));
document.getElementById('btn-log-win').addEventListener('click',()=>openLog('win'));
document.getElementById('btn-log-back').addEventListener('click',closeLog);
show('ts');requestAnimationFrame(loop);
</script>
</body>
</html>"""

display(HTML(
    '<div style="width:100%;border-radius:12px;overflow:hidden;'
    'border:2px solid #ffe135;box-shadow:0 0 30px rgba(255,225,53,0.2)">'
    + GAME_HTML + '</div>'
))

print("""
╔══════════════════════════════════════════════════════════════════╗
║         POO QUEST PLATFORMER v4.0 — Pikachu Edition            ║
║                    UNAB 2026                                     ║
╠══════════════════════════════════════════════════════════════════╣
║  CONTROLES:                                                      ║
║  ← → Mover  |  ↑ / ESPACIO Saltar                              ║
║  Z / botón ⚡ = Lanzar RAYO Thunderbolt (3 por nivel)          ║
║  Pisa enemigos desde arriba (+100) | Rayo (+150)               ║
╚══════════════════════════════════════════════════════════════════╝
""")