# -*- coding: utf-8 -*-
"""tanques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RCk0m2KqUp97bsXj_ZSWpDq2sRWoX8O
"""

from IPython.display import display, HTML

html_code = """
<canvas id="c" width="820" height="540" style="display:block;background:#111;border:2px solid #333;margin:8px auto;border-radius:8px"></canvas>
<div id="ui" style="width:820px;margin:0 auto;display:flex;justify-content:space-between;align-items:center;padding:6px 0;font-family:monospace;color:#ccc;font-size:13px">
  <span id="hpbar">HP: 100</span>
  <span id="biome-name" style="font-weight:bold;color:#ff6600">[ LAVA ]</span>
  <span id="round-display">Ronda 1 / 5</span>
  <span id="score">Bajas: 0</span>
</div>
<p style="width:820px;margin:4px auto;font-family:monospace;color:#555;font-size:11px;text-align:center">
  W A S D = mover | SPACE = disparar | haz clic en el canvas primero
</p>

<script>
const canvas = document.getElementById('c');
const ctx = canvas.getContext('2d');
const W = 820, H = 540;

let round = 1, kills = 0, gameOver = false, won = false;
const ROUNDS = 5;
const keys = {};
let frameCount = 0;
let particles = [], explosions = [];
let playerBullets = [], enemyBullets = [], enemies = [];

const BIOMES = [
  { name:'[ LAVA ]',    bgBase:'#1a0500', gridColor:'rgba(255,80,0,0.08)',
    wallFill:'#3d1a00', wallStroke:'#ff6600', wallGlow:'rgba(255,100,0,0.4)',
    pColors:['#ff4500','#ff7700','#ffaa00','#ff2200'], pType:'ember',
    uiColor:'#ff6600', eCols:['#cc2200','#ff5500','#aa1100','#ee3300'] },
  { name:'[ HIELO ]',   bgBase:'#020d1a', gridColor:'rgba(100,200,255,0.06)',
    wallFill:'#0a2a3d', wallStroke:'#44aadd', wallGlow:'rgba(100,200,255,0.3)',
    pColors:['#aaeeff','#88ccff','#ffffff','#66bbee'], pType:'snow',
    uiColor:'#44ccff', eCols:['#1166aa','#2288cc','#0055aa','#3399cc'] },
  { name:'[ TORNADO ]', bgBase:'#0a0a0f', gridColor:'rgba(180,180,220,0.05)',
    wallFill:'#1a1a22', wallStroke:'#9999bb', wallGlow:'rgba(180,180,255,0.2)',
    pColors:['#aaaacc','#888899','#ccccdd','#666677'], pType:'debris',
    uiColor:'#aaaacc', eCols:['#556677','#778899','#445566','#667788'] },
  { name:'[ BOSQUE ]',  bgBase:'#010a02', gridColor:'rgba(0,180,50,0.05)',
    wallFill:'#071a08', wallStroke:'#228833', wallGlow:'rgba(0,200,50,0.25)',
    pColors:['#22aa44','#44cc66','#116622','#33bb55'], pType:'leaf',
    uiColor:'#33cc55', eCols:['#1a5522','#2a7733','#114411','#3a6622'] },
  { name:'[ VOLCAN ]',  bgBase:'#0f0800', gridColor:'rgba(255,180,0,0.07)',
    wallFill:'#2a1a00', wallStroke:'#ffaa00', wallGlow:'rgba(255,180,0,0.4)',
    pColors:['#ffcc00','#ff9900','#ffee44','#ff6600'], pType:'spark',
    uiColor:'#ffcc00', eCols:['#cc8800','#ffaa00','#aa6600','#ee9900'] },
];

// REGLA: ninguna pared tiene x < 170 (spawn jugador x:80 y:270 siempre libre)
// REGLA: spawn enemigos zona x > 600
const WALL_LAYOUTS = [
  // 0 LAVA
  [ {x:220,y:60,w:24,h:140},{x:220,y:340,w:24,h:140},
    {x:410,y:120,w:24,h:300},{x:590,y:50,w:24,h:120},
    {x:590,y:370,w:24,h:120},{x:670,y:200,w:110,h:24},
    {x:300,y:0,w:110,h:24},{x:300,y:516,w:110,h:24} ],
  // 1 HIELO
  [ {x:200,y:80,w:170,h:20},{x:480,y:80,w:170,h:20},
    {x:200,y:440,w:170,h:20},{x:480,y:440,w:170,h:20},
    {x:410,y:180,w:20,h:180},{x:490,y:290,w:110,h:20},
    {x:350,y:0,w:20,h:55},{x:350,y:485,w:20,h:55} ],
  // 2 TORNADO (sin nada en x < 210, spawn x:80 y:270 completamente libre)
  [ {x:210,y:60,w:20,h:150},{x:700,y:60,w:20,h:150},
    {x:210,y:330,w:20,h:150},{x:700,y:330,w:20,h:150},
    {x:310,y:155,w:140,h:20},{x:500,y:155,w:140,h:20},
    {x:310,y:365,w:140,h:20},{x:500,y:365,w:140,h:20},
    {x:405,y:245,w:55,h:55} ],
  // 3 BOSQUE (columnas desde x:210)
  [ {x:210,y:60,w:20,h:150},{x:210,y:330,w:20,h:150},
    {x:390,y:60,w:20,h:150},{x:390,y:330,w:20,h:150},
    {x:570,y:60,w:20,h:150},{x:570,y:330,w:20,h:150},
    {x:700,y:80,w:20,h:120},{x:700,y:340,w:20,h:120},
    {x:210,y:245,w:120,h:20},{x:580,y:285,w:100,h:20} ],
  // 4 VOLCAN
  [ {x:220,y:60,w:28,h:160},{x:220,y:320,w:28,h:160},
    {x:410,y:100,w:28,h:340},{x:590,y:40,w:28,h:130},
    {x:590,y:370,w:28,h:130},{x:665,y:210,w:120,h:28},
    {x:300,y:0,w:130,h:24},{x:300,y:516,w:130,h:24} ],
];

let biome = BIOMES[0];
let walls = WALL_LAYOUTS[0];

let player = { x:80, y:270, angle:0, hp:100, maxHp:100, speed:2.8, size:15, shootCooldown:0, trail:[] };

function rectHit(bx,by,r,w){ return bx+r>w.x && bx-r<w.x+w.w && by+r>w.y && by-r<w.y+w.h; }
function clamp(v,lo,hi){ return Math.max(lo,Math.min(hi,v)); }
function dist(a,b){ return Math.hypot(a.x-b.x,a.y-b.y); }

// Saca al jugador de cualquier pared
function unstuck() {
  const s = player.size;
  if (!walls.some(w=>rectHit(player.x,player.y,s,w))) return;
  const cands = [
    {x:80,y:270},{x:80,y:200},{x:80,y:340},{x:80,y:130},{x:80,y:410},
    {x:80,y:60},{x:80,y:480},{x:140,y:270},{x:140,y:200},{x:140,y:340},
    {x:50,y:270},{x:50,y:200},{x:50,y:340},{x:50,y:130},{x:50,y:410}
  ];
  for (const c of cands) {
    if (!walls.some(w=>rectHit(c.x,c.y,s,w))) { player.x=c.x; player.y=c.y; return; }
  }
  for (let gx=30;gx<400;gx+=25) {
    for (let gy=25;gy<H-25;gy+=25) {
      if (!walls.some(w=>rectHit(gx,gy,s,w))) { player.x=gx; player.y=gy; return; }
    }
  }
}

function spawnParticles(idx) {
  particles = [];
  const b = BIOMES[idx];
  for (let i=0;i<80;i++){
    const col=b.pColors[Math.floor(Math.random()*b.pColors.length)];
    particles.push({x:Math.random()*W,y:Math.random()*H,size:Math.random()*3+1,
      vx:(Math.random()-0.5)*0.8,vy:Math.random()*-0.5-0.2,alpha:Math.random()*0.7+0.3,
      color:col,phase:Math.random()*Math.PI*2,type:b.pType,
      life:Math.random()*200+100,maxLife:300,
      rotation:Math.random()*Math.PI*2,rotSpeed:(Math.random()-0.5)*0.1});
  }
}

function updateParticles() {
  const b=biome;
  for (const p of particles){
    p.phase+=0.02; p.rotation+=p.rotSpeed; p.life--;
    p.alpha=(p.life/p.maxLife)*0.8;
    if(b.pType==='ember'||b.pType==='spark'){p.x+=p.vx+Math.sin(p.phase)*0.4;p.y+=p.vy;p.size*=0.996;}
    else if(b.pType==='snow'){p.x+=p.vx+Math.sin(p.phase)*0.5;p.y+=0.3+Math.sin(p.phase)*0.2;}
    else if(b.pType==='debris'){p.x+=p.vx*2+Math.sin(frameCount*0.02+p.phase)*2;p.y+=Math.sin(p.phase*0.7)*0.8;}
    else if(b.pType==='leaf'){p.x+=Math.sin(p.phase)*0.8;p.y+=0.4+Math.cos(p.phase*0.6)*0.3;}
    if(p.y<-20||p.y>H+20||p.x<-20||p.x>W+20||p.life<=0){
      const col=b.pColors[Math.floor(Math.random()*b.pColors.length)];
      p.x=Math.random()*W;
      p.y=(b.pType==='snow'||b.pType==='leaf')?-10:H+10;
      if(b.pType==='debris'){p.x=-10;p.y=Math.random()*H;}
      p.color=col;p.life=p.maxLife;p.size=Math.random()*3+1;
      p.alpha=Math.random()*0.7+0.3;p.vx=(Math.random()-0.5)*0.8;p.vy=Math.random()*-0.5-0.2;
    }
  }
}

function drawParticles(){
  ctx.save();
  for(const p of particles){
    ctx.globalAlpha=p.alpha; ctx.fillStyle=p.color; ctx.strokeStyle=p.color;
    if(biome.pType==='snow'){
      ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation);ctx.lineWidth=0.8;
      for(let k=0;k<6;k++){ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,p.size*3);ctx.stroke();ctx.rotate(Math.PI/3);}
      ctx.restore();
    } else if(biome.pType==='leaf'){
      ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation);
      ctx.beginPath();ctx.ellipse(0,0,p.size*1.5,p.size*0.8,0,0,Math.PI*2);ctx.fill();ctx.restore();
    } else if(biome.pType==='debris'){
      ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation);
      ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size);ctx.restore();
    } else {
      ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();
    }
  }
  ctx.globalAlpha=1;ctx.restore();
}

function drawBiomeFX(){
  const t=frameCount;
  if(biome.pType==='debris'){
    ctx.save();ctx.globalAlpha=0.06;
    const cx=W/2,cy=H/2;
    for(let i=0;i<5;i++){
      const r=60+i*40,ang=t*0.015+i*0.4;
      ctx.strokeStyle='#aaaacc';ctx.lineWidth=16-i*2;ctx.beginPath();
      for(let a=0;a<Math.PI*2;a+=0.05){
        const rr=r+Math.sin(a*3+ang)*15;
        const px=cx+Math.cos(a+ang*0.3)*rr,py=cy+Math.sin(a+ang*0.3)*rr*0.5;
        a<0.05?ctx.moveTo(px,py):ctx.lineTo(px,py);
      }
      ctx.stroke();
    }
    ctx.restore();
  }
  if(biome.pType==='ember'||biome.pType==='spark'){
    ctx.save();
    const grad=ctx.createLinearGradient(0,H,0,H-40);
    grad.addColorStop(0,'rgba(255,50,0,'+(0.1+Math.sin(t*0.05)*0.04)+')');
    grad.addColorStop(1,'rgba(0,0,0,0)');
    ctx.fillStyle=grad;ctx.fillRect(0,H-40,W,40);
    ctx.globalAlpha=0.12;ctx.strokeStyle='#ff6600';ctx.lineWidth=1;
    for(let i=0;i<6;i++){
      const ox=(t*0.4+i*130)%W;
      ctx.beginPath();ctx.moveTo(ox,H);ctx.lineTo(ox+40+Math.sin(t*0.07+i)*20,H-80);
      ctx.lineTo(ox+60+Math.cos(t*0.05+i)*15,H-160);ctx.stroke();
    }
    ctx.restore();
  }
  if(biome.pType==='snow'){
    ctx.save();ctx.globalAlpha=0.04+Math.sin(t*0.02)*0.02;
    const g=ctx.createRadialGradient(W/2,H/2,100,W/2,H/2,450);
    g.addColorStop(0,'rgba(150,230,255,0.3)');g.addColorStop(1,'rgba(0,0,0,0)');
    ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.restore();
  }
  if(biome.pType==='leaf'){
    ctx.save();ctx.globalAlpha=0.04+Math.sin(t*0.015)*0.02;
    for(let i=0;i<5;i++){
      const lx=80+i*170;
      const g=ctx.createLinearGradient(lx,0,lx+40,H);
      g.addColorStop(0,'rgba(100,255,100,0.8)');g.addColorStop(1,'rgba(0,80,0,0)');
      ctx.fillStyle=g;ctx.beginPath();
      ctx.moveTo(lx,0);ctx.lineTo(lx+60+Math.sin(t*0.01+i)*10,H);
      ctx.lineTo(lx+20+Math.sin(t*0.01+i)*10,H);ctx.lineTo(lx-20,0);ctx.fill();
    }
    ctx.restore();
  }
}

function drawMap(){
  ctx.fillStyle=biome.bgBase;ctx.fillRect(0,0,W,H);
  ctx.strokeStyle=biome.gridColor;ctx.lineWidth=0.5;
  for(let i=0;i<W;i+=44){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,H);ctx.stroke();}
  for(let j=0;j<H;j+=44){ctx.beginPath();ctx.moveTo(0,j);ctx.lineTo(W,j);ctx.stroke();}
  drawBiomeFX();
  drawParticles();
  walls.forEach(w=>{
    ctx.save();ctx.shadowColor=biome.wallGlow;ctx.shadowBlur=20;
    ctx.fillStyle=biome.wallFill;ctx.fillRect(w.x,w.y,w.w,w.h);ctx.restore();
    ctx.strokeStyle=biome.wallStroke;ctx.lineWidth=1.5;
    ctx.shadowColor=biome.wallStroke;ctx.shadowBlur=8;
    ctx.strokeRect(w.x,w.y,w.w,w.h);ctx.shadowBlur=0;
    ctx.fillStyle='rgba(255,255,255,0.05)';ctx.fillRect(w.x,w.y,w.w,Math.min(4,w.h));
  });
}

function drawTank(t,isPlayer){
  const s=t.size,col=isPlayer?'#4a9eff':t.color,acc=isPlayer?'#88ccff':biome.wallStroke;
  if(t.trail&&t.trail.length>1){
    ctx.save();
    for(let i=0;i<t.trail.length-1;i++){
      ctx.globalAlpha=(i/t.trail.length)*0.12;ctx.fillStyle=col;
      ctx.beginPath();ctx.arc(t.trail[i].x,t.trail[i].y,s*0.4*(i/t.trail.length),0,Math.PI*2);ctx.fill();
    }
    ctx.restore();
  }
  ctx.save();ctx.translate(t.x,t.y);ctx.shadowColor=col;ctx.shadowBlur=12;ctx.rotate(t.angle);
  ctx.fillStyle='rgba(0,0,0,0.4)';ctx.fillRect(-s+3,-s+3,s*2,s*2);
  ctx.fillStyle='rgba(0,0,0,0.5)';ctx.fillRect(-s,-s,5,s*2);ctx.fillRect(s-5,-s,5,s*2);
  ctx.fillStyle=col;ctx.fillRect(-s+5,-s,s*2-10,s*2);
  ctx.fillStyle=acc;ctx.globalAlpha=0.3;ctx.fillRect(-s+5,-s,s*2-10,5);ctx.globalAlpha=1;
  ctx.fillStyle='rgba(0,0,0,0.35)';ctx.beginPath();ctx.arc(0,0,s*0.45,0,Math.PI*2);ctx.fill();
  ctx.fillStyle=col;ctx.beginPath();ctx.arc(0,0,s*0.3,0,Math.PI*2);ctx.fill();
  ctx.shadowBlur=8;ctx.fillStyle=isPlayer?'#2266cc':'#222';ctx.fillRect(-3,-s-16,6,20);
  ctx.fillStyle=acc;ctx.fillRect(-3,-s-20,6,5);
  ctx.restore();ctx.shadowBlur=0;
  const bw=s*2.4,bx=t.x-bw/2,by=t.y-s-14;
  ctx.fillStyle='#111';ctx.fillRect(bx,by,bw,5);
  const pct=Math.max(0,t.hp/t.maxHp);
  const bc=pct>0.5?'#44ff88':pct>0.25?'#ffaa00':'#ff3333';
  ctx.fillStyle=bc;ctx.shadowColor=bc;ctx.shadowBlur=6;ctx.fillRect(bx,by,bw*pct,5);ctx.shadowBlur=0;
}

function drawBullet(b,col,glow){
  ctx.save();ctx.shadowColor=glow||col;ctx.shadowBlur=14;
  ctx.fillStyle=col;ctx.beginPath();ctx.arc(b.x,b.y,5,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#fff';ctx.globalAlpha=0.7;ctx.beginPath();ctx.arc(b.x,b.y,2,0,Math.PI*2);ctx.fill();
  ctx.restore();
}

function spawnEnemies(n){
  const cols=biome.eCols;
  return Array.from({length:n},(_,i)=>({
    x:640+(i%2)*80,y:70+Math.floor(i/2)*100,
    angle:Math.PI,hp:40+round*12,maxHp:40+round*12,
    speed:0.9+round*0.22,size:14,shootTimer:70+i*25,
    color:cols[i%cols.length],moveTimer:0,moveDir:0,trail:[]
  }));
}

function updateEnemy(e){
  e.trail.push({x:e.x,y:e.y});if(e.trail.length>12)e.trail.shift();
  e.moveTimer--;if(e.moveTimer<=0){e.moveTimer=35+Math.random()*45;e.moveDir=Math.random()*Math.PI*2;}
  const toPlayer=Math.atan2(player.y-e.y,player.x-e.x)-Math.PI/2;
  e.angle+=(toPlayer-e.angle)*0.05;
  let nx=e.x+Math.sin(e.moveDir)*e.speed,ny=e.y-Math.cos(e.moveDir)*e.speed;
  if(biome.pType==='debris'){nx+=Math.sin(frameCount*0.02)*0.6;ny+=Math.cos(frameCount*0.015)*0.3;}
  if(!walls.some(w=>rectHit(nx,ny,e.size,w))){
    e.x=clamp(nx,e.size,W-e.size);e.y=clamp(ny,e.size,H-e.size);
  } else {e.moveDir=Math.random()*Math.PI*2;e.moveTimer=30;}
  e.shootTimer--;
  if(e.shootTimer<=0&&dist(e,player)<430){
    e.shootTimer=Math.max(30,80-round*6);
    const a=Math.atan2(player.x-e.x,player.y-e.y);
    enemyBullets.push({x:e.x,y:e.y,vx:Math.sin(a)*5.5,vy:Math.cos(a)*5.5});
  }
}

function updatePlayer(){
  player.trail.push({x:player.x,y:player.y});if(player.trail.length>12)player.trail.shift();
  if(keys['a']||keys['A'])player.angle-=0.055;
  if(keys['d']||keys['D'])player.angle+=0.055;
  if(keys['w']||keys['W']){
    const nx=player.x+Math.sin(player.angle)*player.speed;
    const ny=player.y-Math.cos(player.angle)*player.speed;
    if(!walls.some(w=>rectHit(nx,ny,player.size,w))){
      player.x=clamp(nx,player.size,W-player.size);player.y=clamp(ny,player.size,H-player.size);
    }
  }
  if(keys['s']||keys['S']){
    const nx=player.x-Math.sin(player.angle)*player.speed;
    const ny=player.y+Math.cos(player.angle)*player.speed;
    if(!walls.some(w=>rectHit(nx,ny,player.size,w))){
      player.x=clamp(nx,player.size,W-player.size);player.y=clamp(ny,player.size,H-player.size);
    }
  }
  if(biome.pType==='debris'){
    const drift=Math.sin(frameCount*0.02)*0.5;
    const nx=clamp(player.x+drift,player.size,W-player.size);
    if(!walls.some(w=>rectHit(nx,player.y,player.size,w)))player.x=nx;
  }
  player.shootCooldown--;
  if((keys[' ']||keys['Space'])&&player.shootCooldown<=0){
    player.shootCooldown=16;
    playerBullets.push({
      x:player.x+Math.sin(player.angle)*22,y:player.y-Math.cos(player.angle)*22,
      vx:Math.sin(player.angle)*8,vy:-Math.cos(player.angle)*8
    });
  }
}

function updateBullets(){
  playerBullets=playerBullets.filter(b=>{
    b.x+=b.vx;b.y+=b.vy;
    if(b.x<0||b.x>W||b.y<0||b.y>H)return false;
    if(walls.some(w=>rectHit(b.x,b.y,5,w)))return false;
    for(const e of enemies){if(dist(b,e)<e.size+5){e.hp-=22;spawnExplosion(e.x,e.y);return false;}}
    return true;
  });
  enemyBullets=enemyBullets.filter(b=>{
    b.x+=b.vx;b.y+=b.vy;
    if(b.x<0||b.x>W||b.y<0||b.y>H)return false;
    if(walls.some(w=>rectHit(b.x,b.y,5,w)))return false;
    if(dist(b,player)<player.size+5){player.hp-=9;return false;}
    return true;
  });
  enemies=enemies.filter(e=>{if(e.hp<=0){kills++;return false;}return true;});
}

function spawnExplosion(x,y){
  for(let i=0;i<18;i++){
    const ang=Math.random()*Math.PI*2,spd=Math.random()*4+1;
    explosions.push({x,y,vx:Math.cos(ang)*spd,vy:Math.sin(ang)*spd,
      life:50,maxLife:50,size:Math.random()*5+2,
      color:biome.pColors[Math.floor(Math.random()*biome.pColors.length)]});
  }
}
function updateExplosions(){
  explosions=explosions.filter(p=>{p.x+=p.vx;p.y+=p.vy;p.vx*=0.92;p.vy*=0.92;p.life--;return p.life>0;});
}
function drawExplosions(){
  ctx.save();
  for(const p of explosions){
    ctx.globalAlpha=p.life/p.maxLife;ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=10;
    ctx.beginPath();ctx.arc(p.x,p.y,p.size*(p.life/p.maxLife),0,Math.PI*2);ctx.fill();
  }
  ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.restore();
}

let roundMsg=150,roundMsgText='RONDA 1';

function updateHUD(){
  const pct=Math.max(0,player.hp)/player.maxHp;
  const bars=Math.round(pct*10);
  const fill='|'.repeat(bars)+'.'.repeat(10-bars);
  const el=document.getElementById('hpbar');
  el.textContent='HP ['+fill+'] '+Math.max(0,Math.round(player.hp));
  el.style.color=pct>0.5?'#44ff88':pct>0.25?'#ffaa00':'#ff3333';
  document.getElementById('round-display').textContent='Ronda '+round+' / '+ROUNDS;
  document.getElementById('score').textContent='Bajas: '+kills;
  const bn=document.getElementById('biome-name');
  bn.textContent=biome.name;bn.style.color=biome.uiColor;
}

function drawRoundMsg(){
  if(roundMsg<=0)return;
  const a=Math.min(1,roundMsg/40);
  ctx.save();ctx.globalAlpha=a;
  ctx.fillStyle=biome.uiColor;ctx.shadowColor=biome.uiColor;ctx.shadowBlur=30;
  ctx.font='bold 40px monospace';ctx.textAlign='center';ctx.fillText(roundMsgText,W/2,90);
  ctx.shadowBlur=0;ctx.fillStyle='rgba(255,255,255,0.5)';ctx.font='14px monospace';
  ctx.fillText(enemies.length+' ENEMIGOS  '+biome.name,W/2,118);
  ctx.restore();roundMsg--;
}

function drawEnd(msg,col){
  ctx.fillStyle='rgba(0,0,0,0.78)';ctx.fillRect(0,0,W,H);
  ctx.fillStyle=col;ctx.shadowColor=col;ctx.shadowBlur=50;
  ctx.font='bold 56px monospace';ctx.textAlign='center';ctx.fillText(msg,W/2,H/2-30);
  ctx.shadowBlur=0;ctx.fillStyle='#aaa';ctx.font='16px monospace';
  ctx.fillText('BAJAS TOTALES: '+kills,W/2,H/2+30);
  ctx.fillStyle='#555';ctx.font='13px monospace';
  ctx.fillText('Recarga la celda para jugar de nuevo',W/2,H/2+60);
}

function nextRound(){
  const idx=round%BIOMES.length;
  biome=BIOMES[idx];
  walls=WALL_LAYOUTS[idx];
  spawnParticles(idx);
  player.x=80;player.y=270;player.angle=0;player.trail=[];
  player.hp=Math.min(player.maxHp,player.hp+30);
  playerBullets=[];enemyBullets=[];explosions=[];
  enemies=spawnEnemies(round+1);
  roundMsgText='RONDA '+round;roundMsg=150;
  unstuck();
  Object.keys(keys).forEach(k=>keys[k]=false);
  setTimeout(()=>canvas.focus(),50);
}

function loop(){
  frameCount++;
  if(gameOver){
    drawMap();drawEnd(won?'VICTORIA!':'GAME OVER',won?'#44ff88':'#ff3333');
    updateHUD();requestAnimationFrame(loop);return;
  }
  updatePlayer();enemies.forEach(updateEnemy);
  updateBullets();updateParticles();updateExplosions();
  drawMap();drawExplosions();
  playerBullets.forEach(b=>drawBullet(b,'#ffeb3b','#ffcc00'));
  enemyBullets.forEach(b=>drawBullet(b,'#ff5252','#ff0000'));
  enemies.forEach(e=>drawTank(e,false));
  drawTank(player,true);
  drawRoundMsg();updateHUD();
  if(player.hp<=0){gameOver=true;won=false;}
  if(enemies.length===0){
    if(round>=ROUNDS){gameOver=true;won=true;}
    else{round++;nextRound();}
  }
  requestAnimationFrame(loop);
}

canvas.setAttribute('tabindex','0');
canvas.addEventListener('click',()=>canvas.focus());
canvas.addEventListener('keydown',e=>{keys[e.key]=true;if(e.key===' ')e.preventDefault();});
canvas.addEventListener('keyup',e=>{keys[e.key]=false;});

biome=BIOMES[0];walls=WALL_LAYOUTS[0];spawnParticles(0);
enemies=spawnEnemies(round+1);roundMsgText='RONDA 1';
updateHUD();canvas.focus();loop();
</script>
"""

display(HTML(html_code))