# -*- coding: utf-8 -*-
"""tomodachi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgYI8jEYQzfwHpW4f71At3t7BvRvU0Ic

Aprendiendo a usar print

print() es un metodo que permite imprimir informacion en la consola
"""

# Commented out IPython magic to ensure Python compatibility.
"""
tamagotchi_colab.py  —  Tamagotchi Adventure con animaciones SVG
=================================================================
Corre el juego directamente en Google Colab.
No necesita Tkinter ni display virtual — usa ipywidgets + HTML.

USO EN COLAB:
    1. Sube este archivo a Colab.
    2. En una celda ejecuta:
#            %run tamagotchi_colab.py
       o bien:
           exec(open('tamagotchi_colab.py').read())
"""

# ─── Instalación automática de dependencias ───────────────────────────────────
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "ipywidgets"], check=False)

# ─── Imports ──────────────────────────────────────────────────────────────────
import time, json, os, threading
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# ══════════════════════════════════════════════════════════════════════════════
# CONSTANTES
# ══════════════════════════════════════════════════════════════════════════════
SAVE_FILE           = "tamagotchi_save.json"
TICK_SECONDS        = 5
AUTOSAVE_INTERVAL   = 30

HUNGER_RATE         = 0.40
HAPPINESS_RATE      = 0.20
ENERGY_RATE         = 0.15
HYGIENE_RATE        = 0.08
ENERGY_SLEEP_RATE   = 0.80
HUNGER_SLEEP_RATE   = 0.15
HEALTH_SICK_DECAY   = 0.30
HEALTH_RECOVERY     = 0.05
AUTO_SLEEP_ENERGY   = 10
WAKE_ENERGY         = 95
SICK_HUNGER_TH      = 80
SICK_HYGIENE_TH     = 20

FEED_HUNGER         = 35;  FEED_HAPPY    = 5
PLAY_HAPPY          = 25;  PLAY_ENERGY   = 15;  PLAY_HUNGER  = 8
CLEAN_HYGIENE       = 45;  CLEAN_HAPPY   = 5
HEAL_HEALTH         = 40
PET_HAPPY           = 15;  PET_ENERGY    = 3

STAGES = [(0,"🥚 Huevo"),(2,"🍼 Bebé"),(24,"🐣 Cría"),(72,"🌱 Joven"),(168,"⭐ Adulto"),(720,"👴 Anciano")]

PET_EMOJI = {"Gato":"🐱", "Perro":"🐶", "Dragón":"🐲", "Conejito":"🐰"}
MOOD_EMOJI = {
    "Feliz":"😄","Normal":"🙂","Triste":"😢","Cansado":"😴",
    "Hambriento":"😋","Enfermo":"🤒","Durmiendo":"💤","Muerto":"💀"
}
MOOD_COLOR = {
    "Feliz":"#4CAF50","Normal":"#2196F3","Triste":"#9C27B0",
    "Cansado":"#FF9800","Hambriento":"#FF5722","Enfermo":"#8BC34A",
    "Durmiendo":"#607D8B","Muerto":"#757575"
}

# ══════════════════════════════════════════════════════════════════════════════
# ANIMACIONES SVG — Gato y Perro
# ══════════════════════════════════════════════════════════════════════════════
SVG_CSS = """
<style>
@keyframes pet-idle-body  { 0%,100%{transform:translateY(0)}      50%{transform:translateY(-4px)} }
@keyframes pet-happy-body { 0%,100%{transform:translateY(0) scaleY(1)} 30%{transform:translateY(-10px) scaleY(0.95)} 60%{transform:translateY(0) scaleY(1.05)} }
@keyframes pet-sleep-body { 0%,100%{transform:scaleY(1)}           50%{transform:scaleY(1.04)} }
@keyframes pet-sick-body  { 0%,100%{transform:rotate(0deg)}        25%{transform:rotate(-3deg)} 75%{transform:rotate(3deg)} }
@keyframes pet-dead-body  { 0%{transform:rotate(0deg) translateY(0)} 100%{transform:rotate(90deg) translateY(12px)} }
@keyframes cat-tail-idle  { 0%,100%{transform:rotate(-10deg)} 50%{transform:rotate(10deg)} }
@keyframes cat-tail-happy { 0%,100%{transform:rotate(-25deg)} 50%{transform:rotate(25deg)} }
@keyframes cat-tail-slow  { 0%,100%{transform:rotate(-4deg)}  50%{transform:rotate(4deg)} }
@keyframes dog-tail-idle  { 0%,100%{transform:rotate(-15deg)} 50%{transform:rotate(15deg)} }
@keyframes dog-tail-happy { 0%,100%{transform:rotate(-35deg)} 50%{transform:rotate(35deg)} }
@keyframes pet-ear-twitch { 0%,78%,100%{transform:rotate(0deg)} 83%{transform:rotate(-9deg)} 90%{transform:rotate(0deg)} }
@keyframes pet-ear-flap   { 0%,100%{transform:rotate(0deg)} 30%{transform:rotate(-12deg)} 60%{transform:rotate(8deg)} }
@keyframes pet-blink      { 0%,88%,100%{transform:scaleY(1)} 94%{transform:scaleY(0.05)} }
@keyframes zzz-float      { 0%{transform:translateY(0) scale(.7);opacity:0} 40%{opacity:1} 100%{transform:translateY(-22px) scale(1);opacity:0} }
@keyframes heart-pop      { 0%{transform:scale(0) translateY(0);opacity:1} 100%{transform:scale(1.3) translateY(-20px);opacity:0} }
@keyframes sick-spin      { from{transform:rotate(0deg)} to{transform:rotate(360deg)} }
@keyframes sweat-drop     { 0%,100%{transform:translateY(0);opacity:0} 30%{opacity:1} 80%{transform:translateY(10px);opacity:0.6} }
</style>
"""

def get_pet_svg(pet_type, mood):
    """Retorna HTML+SVG animado según tipo de mascota y estado de ánimo."""

    # ── Paleta de colores ──────────────────────────────────────────────────
    if pet_type == "Gato":
        c_body  = "#FAC775"   # naranja claro
        c_belly = "#FFF3E0"   # crema
        c_dark  = "#EF9F27"   # naranja oscuro
        c_inner = "#F4C0D1"   # rosa oreja
        c_nose  = "#D4537E"
        c_line  = "#BA7517"
        c_eye   = "#2C2C2A"
    else:  # Perro
        c_body  = "#B5D4F4"   # azul claro
        c_belly = "#E6F1FB"   # azul muy claro
        c_dark  = "#85B7EB"   # azul medio
        c_inner = "#E6F1FB"
        c_nose  = "#2C2C2A"
        c_line  = "#185FA5"
        c_eye   = "#2C2C2A"

    # ── Animaciones por estado ─────────────────────────────────────────────
    body_anim = {
        "Feliz":     "pet-happy-body 0.55s ease-in-out infinite",
        "Durmiendo": "pet-sleep-body 3s ease-in-out infinite",
        "Enfermo":   "pet-sick-body 0.55s ease-in-out infinite",
        "Muerto":    "pet-dead-body 0.8s ease-out forwards",
    }.get(mood, "pet-idle-body 2.2s ease-in-out infinite")

    if pet_type == "Gato":
        if mood == "Feliz":
            tail_anim = "cat-tail-happy 0.3s ease-in-out infinite"
        elif mood in ("Durmiendo","Muerto"):
            tail_anim = "cat-tail-slow 5s ease-in-out infinite"
        else:
            tail_anim = "cat-tail-idle 1.8s ease-in-out infinite"
        ear_anim = "pet-ear-flap 0.4s ease-in-out infinite" if mood == "Feliz" else "pet-ear-twitch 3.5s ease-in-out infinite"
    else:  # Perro
        if mood == "Feliz":
            tail_anim = "dog-tail-happy 0.2s ease-in-out infinite"
        elif mood in ("Enfermo","Muerto"):
            tail_anim = "none"
        else:
            tail_anim = "dog-tail-idle 0.65s ease-in-out infinite"
        ear_anim = "pet-ear-flap 0.4s ease-in-out infinite" if mood == "Feliz" else "pet-ear-twitch 3s ease-in-out infinite"

    # ── Extras flotantes ───────────────────────────────────────────────────
    zzz_vis    = "inline" if mood == "Durmiendo" else "none"
    heart_vis  = "inline" if mood == "Feliz"     else "none"
    sick_vis   = "inline" if mood == "Enfermo"   else "none"
    dead_vis   = "inline" if mood == "Muerto"    else "none"

    zzz_html = f"""
      <g style="display:{zzz_vis}">
        <text x="78" y="24" font-size="11" fill="#7F77DD" font-weight="600"
              style="animation:zzz-float 2s ease-out infinite">z</text>
        <text x="85" y="15" font-size="13" fill="#7F77DD" font-weight="600"
              style="animation:zzz-float 2s ease-out infinite;animation-delay:.7s">z</text>
        <text x="93" y="6"  font-size="15" fill="#7F77DD" font-weight="600"
              style="animation:zzz-float 2s ease-out infinite;animation-delay:1.4s">z</text>
      </g>"""

    heart_html = f"""
      <g style="display:{heart_vis}">
        <text x="76" y="28" font-size="14" fill="#D4537E"
              style="animation:heart-pop 1.2s ease-out infinite">♥</text>
        <text x="63" y="20" font-size="11" fill="#D4537E"
              style="animation:heart-pop 1.2s ease-out infinite;animation-delay:.45s">♥</text>
      </g>"""

    sick_html = f"""
      <g style="display:{sick_vis}">
        <text x="74" y="28" font-size="18" fill="#3B6D11"
              style="animation:sick-spin 1.4s linear infinite;transform-origin:83px 21px;display:inline-block">@</text>
        <text x="60" y="16" font-size="10" fill="#3B6D11"
              style="animation:sweat-drop 1.5s ease-in-out infinite;animation-delay:.5s">💧</text>
      </g>"""

    dead_html = f"""
      <g style="display:{dead_vis}">
        <text x="58" y="18" font-size="20" fill="#757575"
              style="animation:heart-pop 2s ease-out infinite">💀</text>
      </g>"""

    # ══ CUERPO DEL GATO ═══════════════════════════════════════════════════
    if pet_type == "Gato":
        if mood == "Feliz":
            mouth_d = "M49 62 Q55 68 61 62"
        elif mood in ("Enfermo","Muerto","Triste","Cansado","Hambriento"):
            mouth_d = "M51 65 Q55 63 59 65"
        else:
            mouth_d = "M52 63 Q55 66 58 63"

        eye_anim_l = "pet-blink 4s ease-in-out infinite"
        eye_anim_r = "pet-blink 4s ease-in-out infinite;animation-delay:.12s"
        if mood == "Durmiendo":
            eye_anim_l = "none"
            eye_anim_r = "none"

        svg_content = f"""
        {zzz_html}{heart_html}{sick_html}{dead_html}

        <g style="transform-origin:55px 70px;animation:{body_anim}">

          <!-- Cola -->
          <g style="transform-origin:30px 90px;animation:{tail_anim}">
            <path d="M30 90 Q10 92 8 76 Q6 63 20 61"
                  fill="none" stroke="{c_dark}" stroke-width="8" stroke-linecap="round"/>
            <path d="M30 90 Q10 92 8 76 Q6 63 20 61"
                  fill="none" stroke="{c_body}" stroke-width="4" stroke-linecap="round" opacity=".5"/>
          </g>

          <!-- Cuerpo -->
          <ellipse cx="55" cy="83" rx="28" ry="21" fill="{c_body}"/>
          <ellipse cx="55" cy="84" rx="18" ry="13" fill="{c_belly}" opacity=".65"/>
          <!-- Rayas dorso -->
          <line x1="46" y1="64" x2="44" y2="72" stroke="{c_dark}" stroke-width="1.5" opacity=".4" stroke-linecap="round"/>
          <line x1="55" y1="62" x2="55" y2="70" stroke="{c_dark}" stroke-width="1.5" opacity=".4" stroke-linecap="round"/>
          <line x1="64" y1="64" x2="66" y2="72" stroke="{c_dark}" stroke-width="1.5" opacity=".4" stroke-linecap="round"/>

          <!-- Patas delanteras -->
          <rect x="37" y="96" width="11" height="15" rx="5.5" fill="{c_body}"/>
          <rect x="67" y="96" width="11" height="15" rx="5.5" fill="{c_body}"/>
          <!-- Patitas -->
          <ellipse cx="42.5" cy="112" rx="6.5" ry="4" fill="{c_dark}"/>
          <ellipse cx="72.5" cy="112" rx="6.5" ry="4" fill="{c_dark}"/>

          <!-- Cabeza -->
          <ellipse cx="55" cy="55" rx="22" ry="20" fill="{c_body}"/>

          <!-- Orejas -->
          <g style="transform-origin:38px 40px;animation:{ear_anim}">
            <polygon points="38,40 30,22 46,30" fill="{c_body}"/>
            <polygon points="38,40 33,28 43,33" fill="{c_inner}" opacity=".85"/>
          </g>
          <g style="transform-origin:72px 40px;animation:{ear_anim};animation-delay:.55s">
            <polygon points="72,40 64,22 80,30" fill="{c_body}"/>
            <polygon points="72,40 67,28 77,33" fill="{c_inner}" opacity=".85"/>
          </g>

          <!-- Ojos -->
          {'<!-- ojos cerrados --><line x1="41" y1="54" x2="51" y2="54" stroke="' + c_eye + '" stroke-width="2.5" stroke-linecap="round"/><line x1="59" y1="54" x2="69" y2="54" stroke="' + c_eye + '" stroke-width="2.5" stroke-linecap="round"/>'
            if mood == "Durmiendo" else
          f'<g style="transform-origin:46px 54px;animation:{eye_anim_l}"><ellipse cx="46" cy="54" rx="5" ry="5.5" fill="{c_eye}"/><circle cx="47.5" cy="52.5" r="1.5" fill="white"/></g><g style="transform-origin:64px 54px;animation:{eye_anim_r}"><ellipse cx="64" cy="54" rx="5" ry="5.5" fill="{c_eye}"/><circle cx="65.5" cy="52.5" r="1.5" fill="white"/></g>'
          }

          <!-- Nariz y boca -->
          <polygon points="55,61 52,58 58,58" fill="{c_nose}"/>
          <path d="{mouth_d}" fill="none" stroke="{c_line}" stroke-width="1.5" stroke-linecap="round"/>

          <!-- Bigotes -->
          <line x1="33" y1="61" x2="48" y2="62" stroke="#888780" stroke-width="1" opacity=".6"/>
          <line x1="33" y1="64" x2="48" y2="64" stroke="#888780" stroke-width="1" opacity=".6"/>
          <line x1="62" y1="62" x2="77" y2="61" stroke="#888780" stroke-width="1" opacity=".6"/>
          <line x1="62" y1="64" x2="77" y2="64" stroke="#888780" stroke-width="1" opacity=".6"/>
        </g>"""

    # ══ CUERPO DEL PERRO ══════════════════════════════════════════════════
    else:
        if mood == "Feliz":
            mouth_d = "M50 65 Q58 72 66 65"
        elif mood in ("Enfermo","Muerto","Triste","Cansado","Hambriento"):
            mouth_d = "M53 68 Q58 65 63 68"
        else:
            mouth_d = "M53 66 Q58 70 63 66"

        tongue = (f'<ellipse cx="58" cy="73" rx="5" ry="6.5" fill="#ED93B1"/>'
                  f'<line x1="58" y1="67" x2="58" y2="79" stroke="#D4537E" stroke-width="1" opacity=".5"/>'
                  if mood == "Feliz" else "")

        eye_anim_l = "pet-blink 3.5s ease-in-out infinite"
        eye_anim_r = "pet-blink 3.5s ease-in-out infinite;animation-delay:.2s"
        if mood == "Durmiendo":
            eye_anim_l = "none"
            eye_anim_r = "none"

        svg_content = f"""
        {zzz_html}{heart_html}{sick_html}{dead_html}

        <g style="transform-origin:58px 72px;animation:{body_anim}">

          <!-- Cola -->
          <g style="transform-origin:84px 83px;animation:{tail_anim}">
            <path d="M84 83 Q97 77 101 63 Q104 52 97 48"
                  fill="none" stroke="{c_dark}" stroke-width="9" stroke-linecap="round"/>
            <path d="M84 83 Q97 77 101 63 Q104 52 97 48"
                  fill="none" stroke="{c_body}" stroke-width="5" stroke-linecap="round" opacity=".5"/>
          </g>

          <!-- Cuerpo -->
          <ellipse cx="58" cy="83" rx="30" ry="22" fill="{c_body}"/>
          <ellipse cx="54" cy="84" rx="20" ry="13" fill="{c_belly}" opacity=".7"/>

          <!-- Patas delanteras -->
          <rect x="38" y="97" width="12" height="17" rx="6" fill="{c_body}"/>
          <rect x="68" y="97" width="12" height="17" rx="6" fill="{c_body}"/>
          <!-- Patitas -->
          <ellipse cx="44"  cy="115" rx="7.5" ry="4.5" fill="{c_dark}"/>
          <ellipse cx="74"  cy="115" rx="7.5" ry="4.5" fill="{c_dark}"/>

          <!-- Cabeza -->
          <ellipse cx="58" cy="54" rx="24" ry="22" fill="{c_body}"/>
          <!-- Hocico -->
          <ellipse cx="58" cy="63" rx="13" ry="9" fill="{c_belly}"/>

          <!-- Orejas caídas -->
          <g style="transform-origin:40px 47px;animation:{ear_anim}">
            <ellipse cx="37" cy="57" rx="11" ry="17" fill="{c_dark}" transform="rotate(-14,37,57)"/>
            <ellipse cx="37" cy="57" rx="7"  ry="12" fill="{c_body}" opacity=".35" transform="rotate(-14,37,57)"/>
          </g>
          <g style="transform-origin:76px 47px;animation:{ear_anim};animation-delay:.3s">
            <ellipse cx="79" cy="57" rx="11" ry="17" fill="{c_dark}" transform="rotate(14,79,57)"/>
            <ellipse cx="79" cy="57" rx="7"  ry="12" fill="{c_body}" opacity=".35" transform="rotate(14,79,57)"/>
          </g>

          <!-- Ojos -->
          {'<!-- ojos cerrados --><line x1="43" y1="51" x2="53" y2="51" stroke="' + c_eye + '" stroke-width="2.5" stroke-linecap="round"/><line x1="63" y1="51" x2="73" y2="51" stroke="' + c_eye + '" stroke-width="2.5" stroke-linecap="round"/>'
            if mood == "Durmiendo" else
          f'<g style="transform-origin:48px 51px;animation:{eye_anim_l}"><ellipse cx="48" cy="51" rx="5.5" ry="5.5" fill="{c_eye}"/><circle cx="49.5" cy="49.5" r="1.5" fill="white"/></g><g style="transform-origin:68px 51px;animation:{eye_anim_r}"><ellipse cx="68" cy="51" rx="5.5" ry="5.5" fill="{c_eye}"/><circle cx="69.5" cy="49.5" r="1.5" fill="white"/></g>'
          }

          <!-- Nariz -->
          <ellipse cx="58" cy="61" rx="5.5" ry="4" fill="{c_nose}"/>
          <circle  cx="56.5" cy="60" r="1" fill="white" opacity=".6"/>

          <!-- Boca y lengua -->
          <path d="{mouth_d}" fill="none" stroke="{c_line}" stroke-width="1.5" stroke-linecap="round"/>
          {tongue}
        </g>"""

    return f"""
{SVG_CSS}
<svg width="130" height="132" viewBox="0 0 130 132" style="overflow:visible;display:block;margin:auto">
  {svg_content}
</svg>"""


# ══════════════════════════════════════════════════════════════════════════════
# CLASE PET
# ══════════════════════════════════════════════════════════════════════════════
class Pet:
    def __init__(self, name, pet_type):
        self.name        = name
        self.pet_type    = pet_type
        self.hunger      = 20.0
        self.happiness   = 80.0
        self.energy      = 90.0
        self.hygiene     = 100.0
        self.health      = 100.0
        self.age_hours   = 0.0
        self.created_at  = time.time()
        self.last_saved  = time.time()
        self.days_survived = 0
        self.is_sleeping = False
        self.is_sick     = False
        self.is_dead     = False
        self.event_log   = []

    @property
    def stage(self):
        s = STAGES[0][1]
        for h, name in STAGES:
            if self.age_hours >= h:
                s = name
        return s

    @property
    def mood(self):
        if self.is_dead:        return "Muerto"
        if self.is_sleeping:    return "Durmiendo"
        if self.is_sick:        return "Enfermo"
        if self.energy < 20:    return "Cansado"
        if self.hunger > 75:    return "Hambriento"
        if self.happiness < 30: return "Triste"
        if self.happiness > 70 and self.hunger < 35 and self.energy > 50:
            return "Feliz"
        return "Normal"

    @property
    def age_display(self):
        d = int(self.age_hours // 24)
        h = int(self.age_hours % 24)
        return f"{d}d {h}h" if d > 0 else f"{h}h"

    def add_event(self, msg):
        ts = time.strftime("%H:%M:%S")
        self.event_log.append(f"[{ts}] {msg}")
        if len(self.event_log) > 40:
            self.event_log.pop(0)

    def to_dict(self):
        return {
            "name": self.name, "pet_type": self.pet_type,
            "hunger": round(self.hunger, 2), "happiness": round(self.happiness, 2),
            "energy": round(self.energy, 2), "hygiene": round(self.hygiene, 2),
            "health": round(self.health, 2), "age_hours": round(self.age_hours, 4),
            "is_sleeping": self.is_sleeping, "is_sick": self.is_sick,
            "is_dead": self.is_dead, "created_at": self.created_at,
            "last_saved": time.time(), "days_survived": self.days_survived,
            "event_log": self.event_log[-30:]
        }

    @classmethod
    def from_dict(cls, d):
        p = cls(d["name"], d["pet_type"])
        for k in ["hunger","happiness","energy","hygiene","health","age_hours"]:
            setattr(p, k, float(d[k]))
        for k in ["is_sleeping","is_sick","is_dead"]:
            setattr(p, k, bool(d[k]))
        p.created_at     = float(d["created_at"])
        p.last_saved     = float(d["last_saved"])
        p.days_survived  = int(d.get("days_survived", 0))
        p.event_log      = list(d.get("event_log", []))
        return p


# ══════════════════════════════════════════════════════════════════════════════
# LÓGICA DEL JUEGO
# ══════════════════════════════════════════════════════════════════════════════
class GameLogic:
    def __init__(self, pet):
        self.pet = pet

    def tick(self):
        p = self.pet
        if p.is_dead: return
        if p.is_sleeping:
            p.energy = min(100, p.energy + ENERGY_SLEEP_RATE)
            p.hunger = min(100, p.hunger + HUNGER_SLEEP_RATE)
            if p.energy >= WAKE_ENERGY:
                p.is_sleeping = False
                p.add_event(f"{p.name} se despertó descansado ☀️")
        else:
            p.hunger    = min(100, p.hunger    + HUNGER_RATE)
            p.happiness = max(0,   p.happiness - HAPPINESS_RATE)
            p.energy    = max(0,   p.energy    - ENERGY_RATE)
            p.hygiene   = max(0,   p.hygiene   - HYGIENE_RATE)

        p.age_hours    += TICK_SECONDS / 3600
        p.days_survived = int(p.age_hours / 24)

        if p.is_sick:
            p.health = max(0, p.health - HEALTH_SICK_DECAY)
        elif p.happiness > 60 and p.hunger < 40 and p.energy > 40:
            p.health = min(100, p.health + HEALTH_RECOVERY)

        if p.energy <= AUTO_SLEEP_ENERGY and not p.is_sleeping:
            p.is_sleeping = True
            p.add_event(f"{p.name} cayó dormido de agotamiento 💤")

        if not p.is_sick and p.hygiene < SICK_HYGIENE_TH and p.hunger > SICK_HUNGER_TH:
            p.is_sick = True
            p.add_event(f"{p.name} se enfermó! ¡Límpialo y aliméntalo!")
        if p.is_sick and p.hygiene > 65 and p.hunger < 30 and p.health > 50:
            p.is_sick = False
            p.add_event(f"{p.name} se recuperó solo gracias al buen cuidado 🌟")

        if p.health <= 0 and not p.is_dead:
            p.is_dead = True
            p.add_event(f"{p.name} ha fallecido 😢")

    def apply_offline(self, elapsed):
        p = self.pet
        if elapsed <= 0 or p.is_dead: return
        ticks = elapsed / TICK_SECONDS
        if p.is_sleeping:
            need  = WAKE_ENERGY - p.energy
            twake = max(0, need / ENERGY_SLEEP_RATE)
            if ticks <= twake:
                p.energy = min(100, p.energy + ENERGY_SLEEP_RATE * ticks)
                p.hunger = min(100, p.hunger + HUNGER_SLEEP_RATE * ticks)
            else:
                p.energy = WAKE_ENERGY
                p.hunger = min(100, p.hunger + HUNGER_SLEEP_RATE * twake)
                p.is_sleeping = False
                aw = ticks - twake
                p.hunger    = min(100, p.hunger    + HUNGER_RATE    * aw)
                p.happiness = max(0,   p.happiness - HAPPINESS_RATE * aw)
                p.energy    = max(0,   p.energy    - ENERGY_RATE    * aw)
                p.hygiene   = max(0,   p.hygiene   - HYGIENE_RATE   * aw)
        else:
            p.hunger    = min(100, p.hunger    + HUNGER_RATE    * ticks)
            p.happiness = max(0,   p.happiness - HAPPINESS_RATE * ticks)
            p.energy    = max(0,   p.energy    - ENERGY_RATE    * ticks)
            p.hygiene   = max(0,   p.hygiene   - HYGIENE_RATE   * ticks)

        p.age_hours    += elapsed / 3600
        p.days_survived = int(p.age_hours / 24)
        if p.is_sick:
            p.health = max(0, p.health - HEALTH_SICK_DECAY * ticks)
        elif p.happiness > 60 and p.hunger < 40 and p.energy > 40:
            p.health = min(100, p.health + HEALTH_RECOVERY * ticks)
        if not p.is_sick and p.hygiene < SICK_HYGIENE_TH and p.hunger > SICK_HUNGER_TH:
            p.is_sick = True
        if p.health <= 0 and not p.is_dead:
            p.is_dead = True

        mins = int(elapsed / 60)
        if mins >= 3:
            h = elapsed / 3600
            p.add_event(f"Estuviste {'%.1f' % h}h fuera." if h >= 1 else f"Estuviste {mins} min fuera.")

    # ── Acciones ──────────────────────────────────────────────────────────
    def _dead(self):
        return f"{self.pet.name} ya no está con nosotros 😢" if self.pet.is_dead else None

    def feed(self):
        e = self._dead()
        if e: return e
        p = self.pet
        if p.is_sleeping: return f"{p.name} está durmiendo."
        if p.hunger <= 5: return f"{p.name} ya está lleno!"
        p.hunger    = max(0,   p.hunger    - FEED_HUNGER)
        p.happiness = min(100, p.happiness + FEED_HAPPY)
        p.add_event(f"{p.name} comió y está satisfecho 🍖")
        return f"¡{p.name} comió!"

    def play(self):
        e = self._dead()
        if e: return e
        p = self.pet
        if p.is_sleeping: return f"{p.name} está durmiendo."
        if p.energy < 15: return f"{p.name} está muy cansado para jugar."
        p.happiness = min(100, p.happiness + PLAY_HAPPY)
        p.energy    = max(0,   p.energy    - PLAY_ENERGY)
        p.hunger    = min(100, p.hunger    + PLAY_HUNGER)
        p.add_event(f"{p.name} jugó y se divirtió mucho 🎮")
        return f"¡{p.name} jugó!"

    def toggle_sleep(self):
        e = self._dead()
        if e: return e
        p = self.pet
        if p.is_sleeping:
            p.is_sleeping = False
            p.add_event(f"{p.name} se despertó.")
            return f"{p.name} se despertó."
        if p.energy >= 90: return f"{p.name} no tiene sueño aún."
        p.is_sleeping = True
        p.add_event(f"{p.name} se fue a dormir 💤")
        return f"{p.name} se fue a dormir."

    def clean(self):
        e = self._dead()
        if e: return e
        p = self.pet
        if p.hygiene >= 95: return f"{p.name} ya está limpio."
        p.hygiene   = min(100, p.hygiene   + CLEAN_HYGIENE)
        p.happiness = min(100, p.happiness + CLEAN_HAPPY)
        p.add_event(f"{p.name} fue bañado y está fresco 🛁")
        return f"¡{p.name} fue limpiado!"

    def heal(self):
        e = self._dead()
        if e: return e
        p = self.pet
        if not p.is_sick and p.health >= 95: return f"{p.name} está sano."
        p.is_sick = False
        p.health  = min(100, p.health + HEAL_HEALTH)
        p.add_event(f"{p.name} recibió medicamento 💊")
        return f"¡{p.name} fue curado!"

    def pet_action(self):
        e = self._dead()
        if e: return e
        p = self.pet
        if p.is_sleeping: return f"No molestes a {p.name} mientras duerme."
        p.happiness = min(100, p.happiness + PET_HAPPY)
        p.energy    = max(0,   p.energy    - PET_ENERGY)
        p.add_event(f"{p.name} disfrutó el cariño ❤️")
        return f"¡Acariciaste a {p.name}!"


# ══════════════════════════════════════════════════════════════════════════════
# STORAGE
# ══════════════════════════════════════════════════════════════════════════════
def save_pet(pet):
    try:
        if os.path.exists(SAVE_FILE):
            import shutil; shutil.copy2(SAVE_FILE, SAVE_FILE + ".bak")
        with open(SAVE_FILE, "w", encoding="utf-8") as f:
            json.dump(pet.to_dict(), f, indent=2, ensure_ascii=False)
    except Exception as ex:
        print(f"[Save error] {ex}")

def load_pet():
    for fp in [SAVE_FILE, SAVE_FILE + ".bak"]:
        if not os.path.exists(fp): continue
        try:
            with open(fp, encoding="utf-8") as f:
                d = json.load(f)
            required = ["name","pet_type","hunger","happiness","energy",
                        "hygiene","health","age_hours","last_saved"]
            if all(k in d for k in required):
                return d
        except: pass
    return None


# ══════════════════════════════════════════════════════════════════════════════
# INTERFAZ COLAB
# ══════════════════════════════════════════════════════════════════════════════
class TamagotchiColab:
    def __init__(self):
        self.pet    = None
        self.logic  = None
        self._timer = None
        self._last_autosave = time.time()
        self._msg   = ""
        self._setup_ui()
        self._load_or_create()

    # ── Widgets ──────────────────────────────────────────────────────────────
    def _setup_ui(self):
        self.out_main = widgets.Output()
        self.out_log  = widgets.Output()
        self.out_msg  = widgets.Output()

        btn_style = dict(button_style='', layout=widgets.Layout(width='128px', height='40px'))
        self.btn_feed   = widgets.Button(description="🍖 Alimentar", **btn_style)
        self.btn_play   = widgets.Button(description="🎮 Jugar",     **btn_style)
        self.btn_sleep  = widgets.Button(description="💤 Dormir",    **btn_style)
        self.btn_clean  = widgets.Button(description="🛁 Limpiar",   **btn_style)
        self.btn_heal   = widgets.Button(description="💊 Curar",     **btn_style)
        self.btn_pet    = widgets.Button(description="❤️ Acariciar", **btn_style)
        self.btn_new    = widgets.Button(description="🔄 Nueva",     **btn_style)
        self.btn_save   = widgets.Button(description="💾 Guardar",   **btn_style)

        for b, fn in [
            (self.btn_feed,  lambda _: self._action(self.logic.feed)),
            (self.btn_play,  lambda _: self._action(self.logic.play)),
            (self.btn_sleep, lambda _: self._action(self.logic.toggle_sleep)),
            (self.btn_clean, lambda _: self._action(self.logic.clean)),
            (self.btn_heal,  lambda _: self._action(self.logic.heal)),
            (self.btn_pet,   lambda _: self._action(self.logic.pet_action)),
            (self.btn_new,   lambda _: self._new_pet()),
            (self.btn_save,  lambda _: self._manual_save()),
        ]:
            b.on_click(fn)

        self.btns = widgets.HBox([
            widgets.VBox([self.btn_feed,  self.btn_play,  self.btn_sleep, self.btn_new]),
            widgets.VBox([self.btn_clean, self.btn_heal,  self.btn_pet,   self.btn_save]),
        ])

    # ── Carga o creación ─────────────────────────────────────────────────────
    def _load_or_create(self):
        data = load_pet()
        if data:
            self.pet   = Pet.from_dict(data)
            self.logic = GameLogic(self.pet)
            elapsed    = min(time.time() - data["last_saved"], 7*24*3600)
            if elapsed > 0:
                self.logic.apply_offline(elapsed)
            self._show()
            self._start_tick()
        else:
            self._creation_screen()

    # ── Pantalla de creación ─────────────────────────────────────────────────
    def _creation_screen(self):
        self._stop_tick()
        display(HTML("""
        <div style="background:#1A1A2E;color:#EAEAEA;padding:24px;border-radius:16px;
                    border:2px solid #E94560;max-width:460px;font-family:monospace;">
          <h2 style="color:#E94560;margin-top:0">🐾 Tamagotchi Adventure</h2>
          <p style="color:#A0A0A0">¡Crea tu nueva mascota!</p>
        </div>
        """))

        name_w = widgets.Text(
            placeholder="Nombre de tu mascota (máx 16)",
            layout=widgets.Layout(width="280px")
        )
        type_w = widgets.RadioButtons(
            options=["🐱 Gato","🐶 Perro","🐲 Dragón","🐰 Conejito"],
            layout=widgets.Layout(width="200px")
        )
        btn_create = widgets.Button(
            description="✨ Crear mascota",
            button_style="success",
            layout=widgets.Layout(width="180px", height="40px")
        )
        out_err = widgets.Output()

        def on_create(_):
            name = name_w.value.strip()[:16]
            if not name:
                with out_err:
                    clear_output(); print("⚠️ Escribe un nombre.")
                return
            ptype = type_w.value.split(" ", 1)[1]
            clear_output(wait=True)
            self.pet   = Pet(name, ptype)
            self.logic = GameLogic(self.pet)
            self.pet.add_event(f"¡Bienvenido, {name}! 🎉")
            save_pet(self.pet)
            self._show()
            self._start_tick()

        btn_create.on_click(on_create)
        display(widgets.VBox([
            widgets.Label("📝 Nombre:"), name_w,
            widgets.Label("🐾 Tipo:"),   type_w,
            btn_create, out_err
        ]))

    # ── Render principal ─────────────────────────────────────────────────────
    def _show(self):
        p = self.pet
        emoji  = PET_EMOJI.get(p.pet_type, "🐾")
        mood   = p.mood
        mcolor = MOOD_COLOR.get(mood, "#888")
        memoji = MOOD_EMOJI.get(mood, "🙂")

        def bar(val, invert=False):
            v   = (100 - val) if invert else val
            pct = max(0, min(100, v))
            if pct > 60:   color = "#4CAF50"
            elif pct > 30: color = "#FFC107"
            else:           color = "#F44336"
            return (
                f'<div style="background:#0F3460;border-radius:6px;height:14px;width:100%;margin:3px 0">'
                f'<div style="background:{color};width:{pct}%;height:100%;border-radius:6px;'
                f'transition:width 0.5s"></div></div>'
            )

        stats_html = f"""
        <div style="font-size:12px">
          <div>🍖 Plenitud &nbsp;{bar(p.hunger, invert=True)}</div>
          <div>😊 Felicidad {bar(p.happiness)}</div>
          <div>⚡ Energía &nbsp;&nbsp;{bar(p.energy)}</div>
          <div>🛁 Higiene &nbsp;&nbsp;{bar(p.hygiene)}</div>
          <div>❤️ Salud &nbsp;&nbsp;&nbsp;&nbsp;{bar(p.health)}</div>
        </div>"""

        sick_badge  = ('<span style="background:#8BC34A;color:#000;padding:2px 8px;'
                       'border-radius:10px;font-size:11px">🤒 Enfermo</span>' if p.is_sick else "")
        sleep_badge = ('<span style="background:#607D8B;color:#fff;padding:2px 8px;'
                       'border-radius:10px;font-size:11px">💤 Durmiendo</span>' if p.is_sleeping else "")
        dead_note   = ('<p style="color:#F44336;font-weight:bold">'
                       'Tu mascota ha fallecido. Crea una nueva con 🔄 Nueva</p>' if p.is_dead else "")

        # ── Mascota visual: SVG animado para Gato/Perro, emoji para otros ──
        use_svg = p.pet_type in ("Gato", "Perro")
        if use_svg:
            pet_visual = get_pet_svg(p.pet_type, mood)
        else:
            big_emoji  = "💀" if p.is_dead else ("💤" if p.is_sleeping else emoji)
            pet_visual = f'<div style="font-size:72px;line-height:1;text-align:center">{big_emoji}</div>'

        html = f"""
        <div style="background:#1A1A2E;color:#EAEAEA;padding:20px;border-radius:16px;
                    border:2px solid #E94560;max-width:460px;font-family:monospace;">

          <!-- Encabezado: info + mascota animada -->
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px">
            <div>
              <span style="font-size:22px;font-weight:bold;color:#E94560">{p.name}</span>
              <span style="color:#A0A0A0;font-size:12px"> — {p.pet_type}</span><br>
              <span style="font-size:11px;color:#A0A0A0">
                {p.stage} · Edad: {p.age_display} · Día {p.days_survived}
              </span>
            </div>
            <div style="min-width:140px;text-align:center">
              {pet_visual}
            </div>
          </div>

          <!-- Estado -->
          <div style="background:{mcolor}22;border:1px solid {mcolor};border-radius:8px;
                      padding:6px 12px;margin-bottom:12px;font-size:13px">
            {memoji} Estado: <strong style="color:{mcolor}">{mood}</strong>
            &nbsp;{sick_badge}{sleep_badge}
          </div>

          <!-- Barras de estadísticas -->
          {stats_html}
          {dead_note}
        </div>"""

        with self.out_main:
            clear_output(wait=True)
            display(HTML(html))

        # Log de eventos
        log_lines = p.event_log[-8:]
        log_html  = "".join(
            f'<div style="font-size:11px;color:#A0A0A0;padding:1px 0">{l}</div>'
            for l in reversed(log_lines)
        )
        with self.out_log:
            clear_output(wait=True)
            display(HTML(
                f'<div style="background:#0d1117;padding:8px;border-radius:8px;'
                f'border:1px solid #30363d;max-width:460px;max-height:140px;overflow-y:auto">'
                f'<div style="font-size:11px;color:#E94560;margin-bottom:4px">📋 Log de eventos</div>'
                f'{log_html}</div>'
            ))

    # ── Mensaje de acción ────────────────────────────────────────────────────
    def _show_msg(self, msg):
        with self.out_msg:
            clear_output(wait=True)
            display(HTML(
                f'<div style="background:#16213E;color:#EAEAEA;padding:6px 12px;'
                f'border-radius:8px;font-family:monospace;font-size:13px;'
                f'border-left:3px solid #E94560;max-width:460px">{msg}</div>'
            ))

    # ── Acciones ─────────────────────────────────────────────────────────────
    def _action(self, fn):
        msg = fn()
        self._show_msg(msg)
        self._show()

    def _manual_save(self):
        save_pet(self.pet)
        self._show_msg("💾 Guardado correctamente.")

    def _new_pet(self):
        self._stop_tick()
        clear_output(wait=True)
        self._creation_screen()

    # ── Tick automático ──────────────────────────────────────────────────────
    def _start_tick(self):
        self._stop_tick()
        self._tick()

    def _stop_tick(self):
        if self._timer:
            self._timer.cancel()
            self._timer = None

    def _tick(self):
        if self.pet and not self.pet.is_dead:
            self.logic.tick()
            self._show()
            if time.time() - self._last_autosave >= AUTOSAVE_INTERVAL:
                save_pet(self.pet)
                self._last_autosave = time.time()
        self._timer = threading.Timer(TICK_SECONDS, self._tick)
        self._timer.daemon = True
        self._timer.start()

    # ── Mostrar todo ─────────────────────────────────────────────────────────
    def run(self):
        display(HTML("""
        <div style="background:#1A1A2E;color:#E94560;padding:12px 20px;
                    border-radius:12px;font-family:monospace;font-size:20px;
                    font-weight:bold;max-width:460px;border:2px solid #E94560;
                    margin-bottom:8px">
          🐾 Tamagotchi Adventure — con animaciones
        </div>
        """))
        display(self.out_main)
        display(self.out_msg)
        display(self.btns)
        display(self.out_log)


# ══════════════════════════════════════════════════════════════════════════════
# PUNTO DE ENTRADA
# ══════════════════════════════════════════════════════════════════════════════
game = TamagotchiColab()
game.run()